/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GooglerpcStatus } from '../models';
// @ts-ignore
import type { InferenceServiceUpdateInferenceRequest } from '../models';
// @ts-ignore
import type { V1beta1CreateInferenceRequest } from '../models';
// @ts-ignore
import type { V1beta1DeleteInferenceReply } from '../models';
// @ts-ignore
import type { V1beta1Inference } from '../models';
// @ts-ignore
import type { V1beta1ListInferenceReply } from '../models';
// @ts-ignore
import type { V1beta1ListInferenceRequest } from '../models';
/**
 * InferenceServiceApi - axios parameter creator
 * @export
 */
export const InferenceServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {V1beta1CreateInferenceRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceCreateInference: async (body: V1beta1CreateInferenceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('inferenceServiceCreateInference', 'body', body)
            const localVarPath = `/v1beta1/inference`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceDeleteInference: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('inferenceServiceDeleteInference', 'id', id)
            const localVarPath = `/v1beta1/inference/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceGetInference: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('inferenceServiceGetInference', 'id', id)
            const localVarPath = `/v1beta1/inference/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [afterPageToken] 
         * @param {string} [beforePageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceListInference: async (pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, afterPageToken?: string, beforePageToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1beta1/inference`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['pageOffset'] = pageOffset;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (afterPageToken !== undefined) {
                localVarQueryParameter['afterPageToken'] = afterPageToken;
            }

            if (beforePageToken !== undefined) {
                localVarQueryParameter['beforePageToken'] = beforePageToken;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {V1beta1ListInferenceRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceListInference2: async (body: V1beta1ListInferenceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('inferenceServiceListInference2', 'body', body)
            const localVarPath = `/v1beta1/inference/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {InferenceServiceUpdateInferenceRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceUpdateInference: async (id: string, body: InferenceServiceUpdateInferenceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('inferenceServiceUpdateInference', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('inferenceServiceUpdateInference', 'body', body)
            const localVarPath = `/v1beta1/inference/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {InferenceServiceUpdateInferenceRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceUpdateInference2: async (id: string, body: InferenceServiceUpdateInferenceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('inferenceServiceUpdateInference2', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('inferenceServiceUpdateInference2', 'body', body)
            const localVarPath = `/v1beta1/inference/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InferenceServiceApi - functional programming interface
 * @export
 */
export const InferenceServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InferenceServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {V1beta1CreateInferenceRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inferenceServiceCreateInference(body: V1beta1CreateInferenceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1Inference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inferenceServiceCreateInference(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InferenceServiceApi.inferenceServiceCreateInference']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inferenceServiceDeleteInference(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1DeleteInferenceReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inferenceServiceDeleteInference(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InferenceServiceApi.inferenceServiceDeleteInference']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inferenceServiceGetInference(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1Inference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inferenceServiceGetInference(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InferenceServiceApi.inferenceServiceGetInference']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [afterPageToken] 
         * @param {string} [beforePageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inferenceServiceListInference(pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, afterPageToken?: string, beforePageToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ListInferenceReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inferenceServiceListInference(pageOffset, pageSize, search, sort, fields, afterPageToken, beforePageToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InferenceServiceApi.inferenceServiceListInference']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {V1beta1ListInferenceRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inferenceServiceListInference2(body: V1beta1ListInferenceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ListInferenceReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inferenceServiceListInference2(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InferenceServiceApi.inferenceServiceListInference2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {InferenceServiceUpdateInferenceRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inferenceServiceUpdateInference(id: string, body: InferenceServiceUpdateInferenceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1Inference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inferenceServiceUpdateInference(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InferenceServiceApi.inferenceServiceUpdateInference']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {InferenceServiceUpdateInferenceRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inferenceServiceUpdateInference2(id: string, body: InferenceServiceUpdateInferenceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1Inference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inferenceServiceUpdateInference2(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InferenceServiceApi.inferenceServiceUpdateInference2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InferenceServiceApi - factory interface
 * @export
 */
export const InferenceServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InferenceServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {InferenceServiceApiInferenceServiceCreateInferenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceCreateInference(requestParameters: InferenceServiceApiInferenceServiceCreateInferenceRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1Inference> {
            return localVarFp.inferenceServiceCreateInference(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InferenceServiceApiInferenceServiceDeleteInferenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceDeleteInference(requestParameters: InferenceServiceApiInferenceServiceDeleteInferenceRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1DeleteInferenceReply> {
            return localVarFp.inferenceServiceDeleteInference(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InferenceServiceApiInferenceServiceGetInferenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceGetInference(requestParameters: InferenceServiceApiInferenceServiceGetInferenceRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1Inference> {
            return localVarFp.inferenceServiceGetInference(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InferenceServiceApiInferenceServiceListInferenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceListInference(requestParameters: InferenceServiceApiInferenceServiceListInferenceRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ListInferenceReply> {
            return localVarFp.inferenceServiceListInference(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.afterPageToken, requestParameters.beforePageToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InferenceServiceApiInferenceServiceListInference2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceListInference2(requestParameters: InferenceServiceApiInferenceServiceListInference2Request, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ListInferenceReply> {
            return localVarFp.inferenceServiceListInference2(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InferenceServiceApiInferenceServiceUpdateInferenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceUpdateInference(requestParameters: InferenceServiceApiInferenceServiceUpdateInferenceRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1Inference> {
            return localVarFp.inferenceServiceUpdateInference(requestParameters.id, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InferenceServiceApiInferenceServiceUpdateInference2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inferenceServiceUpdateInference2(requestParameters: InferenceServiceApiInferenceServiceUpdateInference2Request, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1Inference> {
            return localVarFp.inferenceServiceUpdateInference2(requestParameters.id, requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for inferenceServiceCreateInference operation in InferenceServiceApi.
 * @export
 * @interface InferenceServiceApiInferenceServiceCreateInferenceRequest
 */
export interface InferenceServiceApiInferenceServiceCreateInferenceRequest {
    /**
     * 
     * @type {V1beta1CreateInferenceRequest}
     * @memberof InferenceServiceApiInferenceServiceCreateInference
     */
    readonly body: V1beta1CreateInferenceRequest
}

/**
 * Request parameters for inferenceServiceDeleteInference operation in InferenceServiceApi.
 * @export
 * @interface InferenceServiceApiInferenceServiceDeleteInferenceRequest
 */
export interface InferenceServiceApiInferenceServiceDeleteInferenceRequest {
    /**
     * 
     * @type {string}
     * @memberof InferenceServiceApiInferenceServiceDeleteInference
     */
    readonly id: string
}

/**
 * Request parameters for inferenceServiceGetInference operation in InferenceServiceApi.
 * @export
 * @interface InferenceServiceApiInferenceServiceGetInferenceRequest
 */
export interface InferenceServiceApiInferenceServiceGetInferenceRequest {
    /**
     * 
     * @type {string}
     * @memberof InferenceServiceApiInferenceServiceGetInference
     */
    readonly id: string
}

/**
 * Request parameters for inferenceServiceListInference operation in InferenceServiceApi.
 * @export
 * @interface InferenceServiceApiInferenceServiceListInferenceRequest
 */
export interface InferenceServiceApiInferenceServiceListInferenceRequest {
    /**
     * 
     * @type {number}
     * @memberof InferenceServiceApiInferenceServiceListInference
     */
    readonly pageOffset?: number

    /**
     * 
     * @type {number}
     * @memberof InferenceServiceApiInferenceServiceListInference
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof InferenceServiceApiInferenceServiceListInference
     */
    readonly search?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof InferenceServiceApiInferenceServiceListInference
     */
    readonly sort?: Array<string>

    /**
     * 
     * @type {string}
     * @memberof InferenceServiceApiInferenceServiceListInference
     */
    readonly fields?: string

    /**
     * 
     * @type {string}
     * @memberof InferenceServiceApiInferenceServiceListInference
     */
    readonly afterPageToken?: string

    /**
     * 
     * @type {string}
     * @memberof InferenceServiceApiInferenceServiceListInference
     */
    readonly beforePageToken?: string
}

/**
 * Request parameters for inferenceServiceListInference2 operation in InferenceServiceApi.
 * @export
 * @interface InferenceServiceApiInferenceServiceListInference2Request
 */
export interface InferenceServiceApiInferenceServiceListInference2Request {
    /**
     * 
     * @type {V1beta1ListInferenceRequest}
     * @memberof InferenceServiceApiInferenceServiceListInference2
     */
    readonly body: V1beta1ListInferenceRequest
}

/**
 * Request parameters for inferenceServiceUpdateInference operation in InferenceServiceApi.
 * @export
 * @interface InferenceServiceApiInferenceServiceUpdateInferenceRequest
 */
export interface InferenceServiceApiInferenceServiceUpdateInferenceRequest {
    /**
     * 
     * @type {string}
     * @memberof InferenceServiceApiInferenceServiceUpdateInference
     */
    readonly id: string

    /**
     * 
     * @type {InferenceServiceUpdateInferenceRequest}
     * @memberof InferenceServiceApiInferenceServiceUpdateInference
     */
    readonly body: InferenceServiceUpdateInferenceRequest
}

/**
 * Request parameters for inferenceServiceUpdateInference2 operation in InferenceServiceApi.
 * @export
 * @interface InferenceServiceApiInferenceServiceUpdateInference2Request
 */
export interface InferenceServiceApiInferenceServiceUpdateInference2Request {
    /**
     * 
     * @type {string}
     * @memberof InferenceServiceApiInferenceServiceUpdateInference2
     */
    readonly id: string

    /**
     * 
     * @type {InferenceServiceUpdateInferenceRequest}
     * @memberof InferenceServiceApiInferenceServiceUpdateInference2
     */
    readonly body: InferenceServiceUpdateInferenceRequest
}

/**
 * InferenceServiceApi - object-oriented interface
 * @export
 * @class InferenceServiceApi
 * @extends {BaseAPI}
 */
export class InferenceServiceApi extends BaseAPI {
    /**
     * 
     * @param {InferenceServiceApiInferenceServiceCreateInferenceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InferenceServiceApi
     */
    public inferenceServiceCreateInference(requestParameters: InferenceServiceApiInferenceServiceCreateInferenceRequest, options?: RawAxiosRequestConfig) {
        return InferenceServiceApiFp(this.configuration).inferenceServiceCreateInference(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {InferenceServiceApiInferenceServiceDeleteInferenceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InferenceServiceApi
     */
    public inferenceServiceDeleteInference(requestParameters: InferenceServiceApiInferenceServiceDeleteInferenceRequest, options?: RawAxiosRequestConfig) {
        return InferenceServiceApiFp(this.configuration).inferenceServiceDeleteInference(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {InferenceServiceApiInferenceServiceGetInferenceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InferenceServiceApi
     */
    public inferenceServiceGetInference(requestParameters: InferenceServiceApiInferenceServiceGetInferenceRequest, options?: RawAxiosRequestConfig) {
        return InferenceServiceApiFp(this.configuration).inferenceServiceGetInference(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {InferenceServiceApiInferenceServiceListInferenceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InferenceServiceApi
     */
    public inferenceServiceListInference(requestParameters: InferenceServiceApiInferenceServiceListInferenceRequest = {}, options?: RawAxiosRequestConfig) {
        return InferenceServiceApiFp(this.configuration).inferenceServiceListInference(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.afterPageToken, requestParameters.beforePageToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {InferenceServiceApiInferenceServiceListInference2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InferenceServiceApi
     */
    public inferenceServiceListInference2(requestParameters: InferenceServiceApiInferenceServiceListInference2Request, options?: RawAxiosRequestConfig) {
        return InferenceServiceApiFp(this.configuration).inferenceServiceListInference2(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {InferenceServiceApiInferenceServiceUpdateInferenceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InferenceServiceApi
     */
    public inferenceServiceUpdateInference(requestParameters: InferenceServiceApiInferenceServiceUpdateInferenceRequest, options?: RawAxiosRequestConfig) {
        return InferenceServiceApiFp(this.configuration).inferenceServiceUpdateInference(requestParameters.id, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {InferenceServiceApiInferenceServiceUpdateInference2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InferenceServiceApi
     */
    public inferenceServiceUpdateInference2(requestParameters: InferenceServiceApiInferenceServiceUpdateInference2Request, options?: RawAxiosRequestConfig) {
        return InferenceServiceApiFp(this.configuration).inferenceServiceUpdateInference2(requestParameters.id, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}

