/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GooglerpcStatus } from '../models';
// @ts-ignore
import type { ModelVersionServiceCreateVersionRequest } from '../models';
// @ts-ignore
import type { ModelVersionServiceListVersion2Request } from '../models';
// @ts-ignore
import type { ModelVersionServiceUpdateVersionRequest } from '../models';
// @ts-ignore
import type { V1beta1DeleteVersionReply } from '../models';
// @ts-ignore
import type { V1beta1ListVersionReply } from '../models';
// @ts-ignore
import type { V1beta1ModelVersion } from '../models';
/**
 * ModelVersionServiceApi - axios parameter creator
 * @export
 */
export const ModelVersionServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} modelId 
         * @param {ModelVersionServiceCreateVersionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceCreateVersion: async (modelId: string, body: ModelVersionServiceCreateVersionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('modelVersionServiceCreateVersion', 'modelId', modelId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('modelVersionServiceCreateVersion', 'body', body)
            const localVarPath = `/v1beta1/model/{modelId}/version`
                .replace(`{${"modelId"}}`, encodeURIComponent(String(modelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} modelId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceDeleteVersion: async (modelId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('modelVersionServiceDeleteVersion', 'modelId', modelId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('modelVersionServiceDeleteVersion', 'id', id)
            const localVarPath = `/v1beta1/model/{modelId}/version/{id}`
                .replace(`{${"modelId"}}`, encodeURIComponent(String(modelId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} modelId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceGetVersion: async (modelId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('modelVersionServiceGetVersion', 'modelId', modelId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('modelVersionServiceGetVersion', 'id', id)
            const localVarPath = `/v1beta1/model/{modelId}/version/{id}`
                .replace(`{${"modelId"}}`, encodeURIComponent(String(modelId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} modelId 
         * @param {string} id 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {boolean} [filterInternal$eq] 
         * @param {boolean} [filterInternal$neq] 
         * @param {boolean} [filterInternal$null] 
         * @param {boolean} [filterInternal$nnull] 
         * @param {string} [afterPageToken] 
         * @param {string} [beforePageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceListVersion: async (modelId: string, id: string, pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, filterInternal$eq?: boolean, filterInternal$neq?: boolean, filterInternal$null?: boolean, filterInternal$nnull?: boolean, afterPageToken?: string, beforePageToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('modelVersionServiceListVersion', 'modelId', modelId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('modelVersionServiceListVersion', 'id', id)
            const localVarPath = `/v1beta1/model/{modelId}/version`
                .replace(`{${"modelId"}}`, encodeURIComponent(String(modelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (pageOffset !== undefined) {
                localVarQueryParameter['pageOffset'] = pageOffset;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (filterId$eq !== undefined) {
                localVarQueryParameter['filter.id.$eq'] = filterId$eq;
            }

            if (filterId$neq !== undefined) {
                localVarQueryParameter['filter.id.$neq'] = filterId$neq;
            }

            if (filterId$contains !== undefined) {
                localVarQueryParameter['filter.id.$contains'] = filterId$contains;
            }

            if (filterId$startsWith !== undefined) {
                localVarQueryParameter['filter.id.$starts_with'] = filterId$startsWith;
            }

            if (filterId$nstartsWith !== undefined) {
                localVarQueryParameter['filter.id.$nstarts_with'] = filterId$nstartsWith;
            }

            if (filterId$endsWith !== undefined) {
                localVarQueryParameter['filter.id.$ends_with'] = filterId$endsWith;
            }

            if (filterId$nendsWith !== undefined) {
                localVarQueryParameter['filter.id.$nends_with'] = filterId$nendsWith;
            }

            if (filterId$in) {
                localVarQueryParameter['filter.id.$in'] = filterId$in;
            }

            if (filterId$nin) {
                localVarQueryParameter['filter.id.$nin'] = filterId$nin;
            }

            if (filterId$null !== undefined) {
                localVarQueryParameter['filter.id.$null'] = filterId$null;
            }

            if (filterId$nnull !== undefined) {
                localVarQueryParameter['filter.id.$nnull'] = filterId$nnull;
            }

            if (filterId$empty !== undefined) {
                localVarQueryParameter['filter.id.$empty'] = filterId$empty;
            }

            if (filterId$nempty !== undefined) {
                localVarQueryParameter['filter.id.$nempty'] = filterId$nempty;
            }

            if (filterId$like !== undefined) {
                localVarQueryParameter['filter.id.$like'] = filterId$like;
            }

            if (filterName$eq !== undefined) {
                localVarQueryParameter['filter.name.$eq'] = filterName$eq;
            }

            if (filterName$neq !== undefined) {
                localVarQueryParameter['filter.name.$neq'] = filterName$neq;
            }

            if (filterName$contains !== undefined) {
                localVarQueryParameter['filter.name.$contains'] = filterName$contains;
            }

            if (filterName$startsWith !== undefined) {
                localVarQueryParameter['filter.name.$starts_with'] = filterName$startsWith;
            }

            if (filterName$nstartsWith !== undefined) {
                localVarQueryParameter['filter.name.$nstarts_with'] = filterName$nstartsWith;
            }

            if (filterName$endsWith !== undefined) {
                localVarQueryParameter['filter.name.$ends_with'] = filterName$endsWith;
            }

            if (filterName$nendsWith !== undefined) {
                localVarQueryParameter['filter.name.$nends_with'] = filterName$nendsWith;
            }

            if (filterName$in) {
                localVarQueryParameter['filter.name.$in'] = filterName$in;
            }

            if (filterName$nin) {
                localVarQueryParameter['filter.name.$nin'] = filterName$nin;
            }

            if (filterName$null !== undefined) {
                localVarQueryParameter['filter.name.$null'] = filterName$null;
            }

            if (filterName$nnull !== undefined) {
                localVarQueryParameter['filter.name.$nnull'] = filterName$nnull;
            }

            if (filterName$empty !== undefined) {
                localVarQueryParameter['filter.name.$empty'] = filterName$empty;
            }

            if (filterName$nempty !== undefined) {
                localVarQueryParameter['filter.name.$nempty'] = filterName$nempty;
            }

            if (filterName$like !== undefined) {
                localVarQueryParameter['filter.name.$like'] = filterName$like;
            }

            if (filterInternal$eq !== undefined) {
                localVarQueryParameter['filter.internal.$eq'] = filterInternal$eq;
            }

            if (filterInternal$neq !== undefined) {
                localVarQueryParameter['filter.internal.$neq'] = filterInternal$neq;
            }

            if (filterInternal$null !== undefined) {
                localVarQueryParameter['filter.internal.$null'] = filterInternal$null;
            }

            if (filterInternal$nnull !== undefined) {
                localVarQueryParameter['filter.internal.$nnull'] = filterInternal$nnull;
            }

            if (afterPageToken !== undefined) {
                localVarQueryParameter['afterPageToken'] = afterPageToken;
            }

            if (beforePageToken !== undefined) {
                localVarQueryParameter['beforePageToken'] = beforePageToken;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} modelId 
         * @param {ModelVersionServiceListVersion2Request} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceListVersion2: async (modelId: string, body: ModelVersionServiceListVersion2Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('modelVersionServiceListVersion2', 'modelId', modelId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('modelVersionServiceListVersion2', 'body', body)
            const localVarPath = `/v1beta1/model/{modelId}/version/list`
                .replace(`{${"modelId"}}`, encodeURIComponent(String(modelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} versionModelId 
         * @param {string} versionId 
         * @param {ModelVersionServiceUpdateVersionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceUpdateVersion: async (versionModelId: string, versionId: string, body: ModelVersionServiceUpdateVersionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'versionModelId' is not null or undefined
            assertParamExists('modelVersionServiceUpdateVersion', 'versionModelId', versionModelId)
            // verify required parameter 'versionId' is not null or undefined
            assertParamExists('modelVersionServiceUpdateVersion', 'versionId', versionId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('modelVersionServiceUpdateVersion', 'body', body)
            const localVarPath = `/v1beta1/model/{version.modelId}/version/{version.id}`
                .replace(`{${"version.modelId"}}`, encodeURIComponent(String(versionModelId)))
                .replace(`{${"version.id"}}`, encodeURIComponent(String(versionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} versionModelId 
         * @param {string} versionId 
         * @param {ModelVersionServiceUpdateVersionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceUpdateVersion2: async (versionModelId: string, versionId: string, body: ModelVersionServiceUpdateVersionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'versionModelId' is not null or undefined
            assertParamExists('modelVersionServiceUpdateVersion2', 'versionModelId', versionModelId)
            // verify required parameter 'versionId' is not null or undefined
            assertParamExists('modelVersionServiceUpdateVersion2', 'versionId', versionId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('modelVersionServiceUpdateVersion2', 'body', body)
            const localVarPath = `/v1beta1/model/{version.modelId}/version/{version.id}`
                .replace(`{${"version.modelId"}}`, encodeURIComponent(String(versionModelId)))
                .replace(`{${"version.id"}}`, encodeURIComponent(String(versionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModelVersionServiceApi - functional programming interface
 * @export
 */
export const ModelVersionServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModelVersionServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} modelId 
         * @param {ModelVersionServiceCreateVersionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelVersionServiceCreateVersion(modelId: string, body: ModelVersionServiceCreateVersionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ModelVersion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelVersionServiceCreateVersion(modelId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelVersionServiceApi.modelVersionServiceCreateVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} modelId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelVersionServiceDeleteVersion(modelId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1DeleteVersionReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelVersionServiceDeleteVersion(modelId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelVersionServiceApi.modelVersionServiceDeleteVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} modelId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelVersionServiceGetVersion(modelId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ModelVersion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelVersionServiceGetVersion(modelId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelVersionServiceApi.modelVersionServiceGetVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} modelId 
         * @param {string} id 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {boolean} [filterInternal$eq] 
         * @param {boolean} [filterInternal$neq] 
         * @param {boolean} [filterInternal$null] 
         * @param {boolean} [filterInternal$nnull] 
         * @param {string} [afterPageToken] 
         * @param {string} [beforePageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelVersionServiceListVersion(modelId: string, id: string, pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, filterInternal$eq?: boolean, filterInternal$neq?: boolean, filterInternal$null?: boolean, filterInternal$nnull?: boolean, afterPageToken?: string, beforePageToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ListVersionReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelVersionServiceListVersion(modelId, id, pageOffset, pageSize, search, sort, fields, filterId$eq, filterId$neq, filterId$contains, filterId$startsWith, filterId$nstartsWith, filterId$endsWith, filterId$nendsWith, filterId$in, filterId$nin, filterId$null, filterId$nnull, filterId$empty, filterId$nempty, filterId$like, filterName$eq, filterName$neq, filterName$contains, filterName$startsWith, filterName$nstartsWith, filterName$endsWith, filterName$nendsWith, filterName$in, filterName$nin, filterName$null, filterName$nnull, filterName$empty, filterName$nempty, filterName$like, filterInternal$eq, filterInternal$neq, filterInternal$null, filterInternal$nnull, afterPageToken, beforePageToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelVersionServiceApi.modelVersionServiceListVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} modelId 
         * @param {ModelVersionServiceListVersion2Request} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelVersionServiceListVersion2(modelId: string, body: ModelVersionServiceListVersion2Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ListVersionReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelVersionServiceListVersion2(modelId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelVersionServiceApi.modelVersionServiceListVersion2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} versionModelId 
         * @param {string} versionId 
         * @param {ModelVersionServiceUpdateVersionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelVersionServiceUpdateVersion(versionModelId: string, versionId: string, body: ModelVersionServiceUpdateVersionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ModelVersion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelVersionServiceUpdateVersion(versionModelId, versionId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelVersionServiceApi.modelVersionServiceUpdateVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} versionModelId 
         * @param {string} versionId 
         * @param {ModelVersionServiceUpdateVersionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelVersionServiceUpdateVersion2(versionModelId: string, versionId: string, body: ModelVersionServiceUpdateVersionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ModelVersion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelVersionServiceUpdateVersion2(versionModelId, versionId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelVersionServiceApi.modelVersionServiceUpdateVersion2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ModelVersionServiceApi - factory interface
 * @export
 */
export const ModelVersionServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModelVersionServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {ModelVersionServiceApiModelVersionServiceCreateVersionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceCreateVersion(requestParameters: ModelVersionServiceApiModelVersionServiceCreateVersionRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ModelVersion> {
            return localVarFp.modelVersionServiceCreateVersion(requestParameters.modelId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelVersionServiceApiModelVersionServiceDeleteVersionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceDeleteVersion(requestParameters: ModelVersionServiceApiModelVersionServiceDeleteVersionRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1DeleteVersionReply> {
            return localVarFp.modelVersionServiceDeleteVersion(requestParameters.modelId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelVersionServiceApiModelVersionServiceGetVersionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceGetVersion(requestParameters: ModelVersionServiceApiModelVersionServiceGetVersionRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ModelVersion> {
            return localVarFp.modelVersionServiceGetVersion(requestParameters.modelId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelVersionServiceApiModelVersionServiceListVersionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceListVersion(requestParameters: ModelVersionServiceApiModelVersionServiceListVersionRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ListVersionReply> {
            return localVarFp.modelVersionServiceListVersion(requestParameters.modelId, requestParameters.id, requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, requestParameters.filterInternal$eq, requestParameters.filterInternal$neq, requestParameters.filterInternal$null, requestParameters.filterInternal$nnull, requestParameters.afterPageToken, requestParameters.beforePageToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelVersionServiceApiModelVersionServiceListVersion2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceListVersion2(requestParameters: ModelVersionServiceApiModelVersionServiceListVersion2Request, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ListVersionReply> {
            return localVarFp.modelVersionServiceListVersion2(requestParameters.modelId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelVersionServiceApiModelVersionServiceUpdateVersionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceUpdateVersion(requestParameters: ModelVersionServiceApiModelVersionServiceUpdateVersionRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ModelVersion> {
            return localVarFp.modelVersionServiceUpdateVersion(requestParameters.versionModelId, requestParameters.versionId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelVersionServiceApiModelVersionServiceUpdateVersion2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelVersionServiceUpdateVersion2(requestParameters: ModelVersionServiceApiModelVersionServiceUpdateVersion2Request, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ModelVersion> {
            return localVarFp.modelVersionServiceUpdateVersion2(requestParameters.versionModelId, requestParameters.versionId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for modelVersionServiceCreateVersion operation in ModelVersionServiceApi.
 * @export
 * @interface ModelVersionServiceApiModelVersionServiceCreateVersionRequest
 */
export interface ModelVersionServiceApiModelVersionServiceCreateVersionRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceCreateVersion
     */
    readonly modelId: string

    /**
     * 
     * @type {ModelVersionServiceCreateVersionRequest}
     * @memberof ModelVersionServiceApiModelVersionServiceCreateVersion
     */
    readonly body: ModelVersionServiceCreateVersionRequest
}

/**
 * Request parameters for modelVersionServiceDeleteVersion operation in ModelVersionServiceApi.
 * @export
 * @interface ModelVersionServiceApiModelVersionServiceDeleteVersionRequest
 */
export interface ModelVersionServiceApiModelVersionServiceDeleteVersionRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceDeleteVersion
     */
    readonly modelId: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceDeleteVersion
     */
    readonly id: string
}

/**
 * Request parameters for modelVersionServiceGetVersion operation in ModelVersionServiceApi.
 * @export
 * @interface ModelVersionServiceApiModelVersionServiceGetVersionRequest
 */
export interface ModelVersionServiceApiModelVersionServiceGetVersionRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceGetVersion
     */
    readonly modelId: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceGetVersion
     */
    readonly id: string
}

/**
 * Request parameters for modelVersionServiceListVersion operation in ModelVersionServiceApi.
 * @export
 * @interface ModelVersionServiceApiModelVersionServiceListVersionRequest
 */
export interface ModelVersionServiceApiModelVersionServiceListVersionRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly modelId: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly id: string

    /**
     * 
     * @type {number}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly pageOffset?: number

    /**
     * 
     * @type {number}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly search?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly sort?: Array<string>

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly fields?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterId$like?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterName$like?: string

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterInternal$eq?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterInternal$neq?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterInternal$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly filterInternal$nnull?: boolean

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly afterPageToken?: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion
     */
    readonly beforePageToken?: string
}

/**
 * Request parameters for modelVersionServiceListVersion2 operation in ModelVersionServiceApi.
 * @export
 * @interface ModelVersionServiceApiModelVersionServiceListVersion2Request
 */
export interface ModelVersionServiceApiModelVersionServiceListVersion2Request {
    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion2
     */
    readonly modelId: string

    /**
     * 
     * @type {ModelVersionServiceListVersion2Request}
     * @memberof ModelVersionServiceApiModelVersionServiceListVersion2
     */
    readonly body: ModelVersionServiceListVersion2Request
}

/**
 * Request parameters for modelVersionServiceUpdateVersion operation in ModelVersionServiceApi.
 * @export
 * @interface ModelVersionServiceApiModelVersionServiceUpdateVersionRequest
 */
export interface ModelVersionServiceApiModelVersionServiceUpdateVersionRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceUpdateVersion
     */
    readonly versionModelId: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceUpdateVersion
     */
    readonly versionId: string

    /**
     * 
     * @type {ModelVersionServiceUpdateVersionRequest}
     * @memberof ModelVersionServiceApiModelVersionServiceUpdateVersion
     */
    readonly body: ModelVersionServiceUpdateVersionRequest
}

/**
 * Request parameters for modelVersionServiceUpdateVersion2 operation in ModelVersionServiceApi.
 * @export
 * @interface ModelVersionServiceApiModelVersionServiceUpdateVersion2Request
 */
export interface ModelVersionServiceApiModelVersionServiceUpdateVersion2Request {
    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceUpdateVersion2
     */
    readonly versionModelId: string

    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceApiModelVersionServiceUpdateVersion2
     */
    readonly versionId: string

    /**
     * 
     * @type {ModelVersionServiceUpdateVersionRequest}
     * @memberof ModelVersionServiceApiModelVersionServiceUpdateVersion2
     */
    readonly body: ModelVersionServiceUpdateVersionRequest
}

/**
 * ModelVersionServiceApi - object-oriented interface
 * @export
 * @class ModelVersionServiceApi
 * @extends {BaseAPI}
 */
export class ModelVersionServiceApi extends BaseAPI {
    /**
     * 
     * @param {ModelVersionServiceApiModelVersionServiceCreateVersionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelVersionServiceApi
     */
    public modelVersionServiceCreateVersion(requestParameters: ModelVersionServiceApiModelVersionServiceCreateVersionRequest, options?: RawAxiosRequestConfig) {
        return ModelVersionServiceApiFp(this.configuration).modelVersionServiceCreateVersion(requestParameters.modelId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelVersionServiceApiModelVersionServiceDeleteVersionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelVersionServiceApi
     */
    public modelVersionServiceDeleteVersion(requestParameters: ModelVersionServiceApiModelVersionServiceDeleteVersionRequest, options?: RawAxiosRequestConfig) {
        return ModelVersionServiceApiFp(this.configuration).modelVersionServiceDeleteVersion(requestParameters.modelId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelVersionServiceApiModelVersionServiceGetVersionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelVersionServiceApi
     */
    public modelVersionServiceGetVersion(requestParameters: ModelVersionServiceApiModelVersionServiceGetVersionRequest, options?: RawAxiosRequestConfig) {
        return ModelVersionServiceApiFp(this.configuration).modelVersionServiceGetVersion(requestParameters.modelId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelVersionServiceApiModelVersionServiceListVersionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelVersionServiceApi
     */
    public modelVersionServiceListVersion(requestParameters: ModelVersionServiceApiModelVersionServiceListVersionRequest, options?: RawAxiosRequestConfig) {
        return ModelVersionServiceApiFp(this.configuration).modelVersionServiceListVersion(requestParameters.modelId, requestParameters.id, requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, requestParameters.filterInternal$eq, requestParameters.filterInternal$neq, requestParameters.filterInternal$null, requestParameters.filterInternal$nnull, requestParameters.afterPageToken, requestParameters.beforePageToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelVersionServiceApiModelVersionServiceListVersion2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelVersionServiceApi
     */
    public modelVersionServiceListVersion2(requestParameters: ModelVersionServiceApiModelVersionServiceListVersion2Request, options?: RawAxiosRequestConfig) {
        return ModelVersionServiceApiFp(this.configuration).modelVersionServiceListVersion2(requestParameters.modelId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelVersionServiceApiModelVersionServiceUpdateVersionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelVersionServiceApi
     */
    public modelVersionServiceUpdateVersion(requestParameters: ModelVersionServiceApiModelVersionServiceUpdateVersionRequest, options?: RawAxiosRequestConfig) {
        return ModelVersionServiceApiFp(this.configuration).modelVersionServiceUpdateVersion(requestParameters.versionModelId, requestParameters.versionId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelVersionServiceApiModelVersionServiceUpdateVersion2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelVersionServiceApi
     */
    public modelVersionServiceUpdateVersion2(requestParameters: ModelVersionServiceApiModelVersionServiceUpdateVersion2Request, options?: RawAxiosRequestConfig) {
        return ModelVersionServiceApiFp(this.configuration).modelVersionServiceUpdateVersion2(requestParameters.versionModelId, requestParameters.versionId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}

