/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GooglerpcStatus } from '../models';
// @ts-ignore
import type { ModelServiceUpdateModelRequest } from '../models';
// @ts-ignore
import type { V1beta1CreateModelRequest } from '../models';
// @ts-ignore
import type { V1beta1DeleteModelReply } from '../models';
// @ts-ignore
import type { V1beta1ListModelReply } from '../models';
// @ts-ignore
import type { V1beta1ListModelRequest } from '../models';
// @ts-ignore
import type { V1beta1Model } from '../models';
/**
 * ModelServiceApi - axios parameter creator
 * @export
 */
export const ModelServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {V1beta1CreateModelRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceCreateModel: async (body: V1beta1CreateModelRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('modelServiceCreateModel', 'body', body)
            const localVarPath = `/v1beta1/model`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceDeleteModel: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('modelServiceDeleteModel', 'id', id)
            const localVarPath = `/v1beta1/model/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceGetModel: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('modelServiceGetModel', 'id', id)
            const localVarPath = `/v1beta1/model/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {boolean} [filterInternal$eq] 
         * @param {boolean} [filterInternal$neq] 
         * @param {boolean} [filterInternal$null] 
         * @param {boolean} [filterInternal$nnull] 
         * @param {string} [afterPageToken] 
         * @param {string} [beforePageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceListModel: async (pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, filterInternal$eq?: boolean, filterInternal$neq?: boolean, filterInternal$null?: boolean, filterInternal$nnull?: boolean, afterPageToken?: string, beforePageToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1beta1/model`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['pageOffset'] = pageOffset;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (filterId$eq !== undefined) {
                localVarQueryParameter['filter.id.$eq'] = filterId$eq;
            }

            if (filterId$neq !== undefined) {
                localVarQueryParameter['filter.id.$neq'] = filterId$neq;
            }

            if (filterId$contains !== undefined) {
                localVarQueryParameter['filter.id.$contains'] = filterId$contains;
            }

            if (filterId$startsWith !== undefined) {
                localVarQueryParameter['filter.id.$starts_with'] = filterId$startsWith;
            }

            if (filterId$nstartsWith !== undefined) {
                localVarQueryParameter['filter.id.$nstarts_with'] = filterId$nstartsWith;
            }

            if (filterId$endsWith !== undefined) {
                localVarQueryParameter['filter.id.$ends_with'] = filterId$endsWith;
            }

            if (filterId$nendsWith !== undefined) {
                localVarQueryParameter['filter.id.$nends_with'] = filterId$nendsWith;
            }

            if (filterId$in) {
                localVarQueryParameter['filter.id.$in'] = filterId$in;
            }

            if (filterId$nin) {
                localVarQueryParameter['filter.id.$nin'] = filterId$nin;
            }

            if (filterId$null !== undefined) {
                localVarQueryParameter['filter.id.$null'] = filterId$null;
            }

            if (filterId$nnull !== undefined) {
                localVarQueryParameter['filter.id.$nnull'] = filterId$nnull;
            }

            if (filterId$empty !== undefined) {
                localVarQueryParameter['filter.id.$empty'] = filterId$empty;
            }

            if (filterId$nempty !== undefined) {
                localVarQueryParameter['filter.id.$nempty'] = filterId$nempty;
            }

            if (filterId$like !== undefined) {
                localVarQueryParameter['filter.id.$like'] = filterId$like;
            }

            if (filterName$eq !== undefined) {
                localVarQueryParameter['filter.name.$eq'] = filterName$eq;
            }

            if (filterName$neq !== undefined) {
                localVarQueryParameter['filter.name.$neq'] = filterName$neq;
            }

            if (filterName$contains !== undefined) {
                localVarQueryParameter['filter.name.$contains'] = filterName$contains;
            }

            if (filterName$startsWith !== undefined) {
                localVarQueryParameter['filter.name.$starts_with'] = filterName$startsWith;
            }

            if (filterName$nstartsWith !== undefined) {
                localVarQueryParameter['filter.name.$nstarts_with'] = filterName$nstartsWith;
            }

            if (filterName$endsWith !== undefined) {
                localVarQueryParameter['filter.name.$ends_with'] = filterName$endsWith;
            }

            if (filterName$nendsWith !== undefined) {
                localVarQueryParameter['filter.name.$nends_with'] = filterName$nendsWith;
            }

            if (filterName$in) {
                localVarQueryParameter['filter.name.$in'] = filterName$in;
            }

            if (filterName$nin) {
                localVarQueryParameter['filter.name.$nin'] = filterName$nin;
            }

            if (filterName$null !== undefined) {
                localVarQueryParameter['filter.name.$null'] = filterName$null;
            }

            if (filterName$nnull !== undefined) {
                localVarQueryParameter['filter.name.$nnull'] = filterName$nnull;
            }

            if (filterName$empty !== undefined) {
                localVarQueryParameter['filter.name.$empty'] = filterName$empty;
            }

            if (filterName$nempty !== undefined) {
                localVarQueryParameter['filter.name.$nempty'] = filterName$nempty;
            }

            if (filterName$like !== undefined) {
                localVarQueryParameter['filter.name.$like'] = filterName$like;
            }

            if (filterInternal$eq !== undefined) {
                localVarQueryParameter['filter.internal.$eq'] = filterInternal$eq;
            }

            if (filterInternal$neq !== undefined) {
                localVarQueryParameter['filter.internal.$neq'] = filterInternal$neq;
            }

            if (filterInternal$null !== undefined) {
                localVarQueryParameter['filter.internal.$null'] = filterInternal$null;
            }

            if (filterInternal$nnull !== undefined) {
                localVarQueryParameter['filter.internal.$nnull'] = filterInternal$nnull;
            }

            if (afterPageToken !== undefined) {
                localVarQueryParameter['afterPageToken'] = afterPageToken;
            }

            if (beforePageToken !== undefined) {
                localVarQueryParameter['beforePageToken'] = beforePageToken;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {V1beta1ListModelRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceListModel2: async (body: V1beta1ListModelRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('modelServiceListModel2', 'body', body)
            const localVarPath = `/v1beta1/model/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} modelId 
         * @param {ModelServiceUpdateModelRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceUpdateModel: async (modelId: string, body: ModelServiceUpdateModelRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('modelServiceUpdateModel', 'modelId', modelId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('modelServiceUpdateModel', 'body', body)
            const localVarPath = `/v1beta1/model/{model.id}`
                .replace(`{${"model.id"}}`, encodeURIComponent(String(modelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} modelId 
         * @param {ModelServiceUpdateModelRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceUpdateModel2: async (modelId: string, body: ModelServiceUpdateModelRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('modelServiceUpdateModel2', 'modelId', modelId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('modelServiceUpdateModel2', 'body', body)
            const localVarPath = `/v1beta1/model/{model.id}`
                .replace(`{${"model.id"}}`, encodeURIComponent(String(modelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModelServiceApi - functional programming interface
 * @export
 */
export const ModelServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModelServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {V1beta1CreateModelRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelServiceCreateModel(body: V1beta1CreateModelRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1Model>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelServiceCreateModel(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelServiceApi.modelServiceCreateModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelServiceDeleteModel(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1DeleteModelReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelServiceDeleteModel(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelServiceApi.modelServiceDeleteModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelServiceGetModel(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1Model>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelServiceGetModel(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelServiceApi.modelServiceGetModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {boolean} [filterInternal$eq] 
         * @param {boolean} [filterInternal$neq] 
         * @param {boolean} [filterInternal$null] 
         * @param {boolean} [filterInternal$nnull] 
         * @param {string} [afterPageToken] 
         * @param {string} [beforePageToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelServiceListModel(pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, filterInternal$eq?: boolean, filterInternal$neq?: boolean, filterInternal$null?: boolean, filterInternal$nnull?: boolean, afterPageToken?: string, beforePageToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ListModelReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelServiceListModel(pageOffset, pageSize, search, sort, fields, filterId$eq, filterId$neq, filterId$contains, filterId$startsWith, filterId$nstartsWith, filterId$endsWith, filterId$nendsWith, filterId$in, filterId$nin, filterId$null, filterId$nnull, filterId$empty, filterId$nempty, filterId$like, filterName$eq, filterName$neq, filterName$contains, filterName$startsWith, filterName$nstartsWith, filterName$endsWith, filterName$nendsWith, filterName$in, filterName$nin, filterName$null, filterName$nnull, filterName$empty, filterName$nempty, filterName$like, filterInternal$eq, filterInternal$neq, filterInternal$null, filterInternal$nnull, afterPageToken, beforePageToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelServiceApi.modelServiceListModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {V1beta1ListModelRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelServiceListModel2(body: V1beta1ListModelRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1ListModelReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelServiceListModel2(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelServiceApi.modelServiceListModel2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} modelId 
         * @param {ModelServiceUpdateModelRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelServiceUpdateModel(modelId: string, body: ModelServiceUpdateModelRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1Model>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelServiceUpdateModel(modelId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelServiceApi.modelServiceUpdateModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} modelId 
         * @param {ModelServiceUpdateModelRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelServiceUpdateModel2(modelId: string, body: ModelServiceUpdateModelRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1beta1Model>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelServiceUpdateModel2(modelId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelServiceApi.modelServiceUpdateModel2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ModelServiceApi - factory interface
 * @export
 */
export const ModelServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModelServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {ModelServiceApiModelServiceCreateModelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceCreateModel(requestParameters: ModelServiceApiModelServiceCreateModelRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1Model> {
            return localVarFp.modelServiceCreateModel(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelServiceApiModelServiceDeleteModelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceDeleteModel(requestParameters: ModelServiceApiModelServiceDeleteModelRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1DeleteModelReply> {
            return localVarFp.modelServiceDeleteModel(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelServiceApiModelServiceGetModelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceGetModel(requestParameters: ModelServiceApiModelServiceGetModelRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1Model> {
            return localVarFp.modelServiceGetModel(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelServiceApiModelServiceListModelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceListModel(requestParameters: ModelServiceApiModelServiceListModelRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ListModelReply> {
            return localVarFp.modelServiceListModel(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, requestParameters.filterInternal$eq, requestParameters.filterInternal$neq, requestParameters.filterInternal$null, requestParameters.filterInternal$nnull, requestParameters.afterPageToken, requestParameters.beforePageToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelServiceApiModelServiceListModel2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceListModel2(requestParameters: ModelServiceApiModelServiceListModel2Request, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1ListModelReply> {
            return localVarFp.modelServiceListModel2(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelServiceApiModelServiceUpdateModelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceUpdateModel(requestParameters: ModelServiceApiModelServiceUpdateModelRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1Model> {
            return localVarFp.modelServiceUpdateModel(requestParameters.modelId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ModelServiceApiModelServiceUpdateModel2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelServiceUpdateModel2(requestParameters: ModelServiceApiModelServiceUpdateModel2Request, options?: RawAxiosRequestConfig): AxiosPromise<V1beta1Model> {
            return localVarFp.modelServiceUpdateModel2(requestParameters.modelId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for modelServiceCreateModel operation in ModelServiceApi.
 * @export
 * @interface ModelServiceApiModelServiceCreateModelRequest
 */
export interface ModelServiceApiModelServiceCreateModelRequest {
    /**
     * 
     * @type {V1beta1CreateModelRequest}
     * @memberof ModelServiceApiModelServiceCreateModel
     */
    readonly body: V1beta1CreateModelRequest
}

/**
 * Request parameters for modelServiceDeleteModel operation in ModelServiceApi.
 * @export
 * @interface ModelServiceApiModelServiceDeleteModelRequest
 */
export interface ModelServiceApiModelServiceDeleteModelRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceDeleteModel
     */
    readonly id: string
}

/**
 * Request parameters for modelServiceGetModel operation in ModelServiceApi.
 * @export
 * @interface ModelServiceApiModelServiceGetModelRequest
 */
export interface ModelServiceApiModelServiceGetModelRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceGetModel
     */
    readonly id: string
}

/**
 * Request parameters for modelServiceListModel operation in ModelServiceApi.
 * @export
 * @interface ModelServiceApiModelServiceListModelRequest
 */
export interface ModelServiceApiModelServiceListModelRequest {
    /**
     * 
     * @type {number}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly pageOffset?: number

    /**
     * 
     * @type {number}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly search?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly sort?: Array<string>

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly fields?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterId$like?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterName$like?: string

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterInternal$eq?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterInternal$neq?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterInternal$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly filterInternal$nnull?: boolean

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly afterPageToken?: string

    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceListModel
     */
    readonly beforePageToken?: string
}

/**
 * Request parameters for modelServiceListModel2 operation in ModelServiceApi.
 * @export
 * @interface ModelServiceApiModelServiceListModel2Request
 */
export interface ModelServiceApiModelServiceListModel2Request {
    /**
     * 
     * @type {V1beta1ListModelRequest}
     * @memberof ModelServiceApiModelServiceListModel2
     */
    readonly body: V1beta1ListModelRequest
}

/**
 * Request parameters for modelServiceUpdateModel operation in ModelServiceApi.
 * @export
 * @interface ModelServiceApiModelServiceUpdateModelRequest
 */
export interface ModelServiceApiModelServiceUpdateModelRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceUpdateModel
     */
    readonly modelId: string

    /**
     * 
     * @type {ModelServiceUpdateModelRequest}
     * @memberof ModelServiceApiModelServiceUpdateModel
     */
    readonly body: ModelServiceUpdateModelRequest
}

/**
 * Request parameters for modelServiceUpdateModel2 operation in ModelServiceApi.
 * @export
 * @interface ModelServiceApiModelServiceUpdateModel2Request
 */
export interface ModelServiceApiModelServiceUpdateModel2Request {
    /**
     * 
     * @type {string}
     * @memberof ModelServiceApiModelServiceUpdateModel2
     */
    readonly modelId: string

    /**
     * 
     * @type {ModelServiceUpdateModelRequest}
     * @memberof ModelServiceApiModelServiceUpdateModel2
     */
    readonly body: ModelServiceUpdateModelRequest
}

/**
 * ModelServiceApi - object-oriented interface
 * @export
 * @class ModelServiceApi
 * @extends {BaseAPI}
 */
export class ModelServiceApi extends BaseAPI {
    /**
     * 
     * @param {ModelServiceApiModelServiceCreateModelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelServiceApi
     */
    public modelServiceCreateModel(requestParameters: ModelServiceApiModelServiceCreateModelRequest, options?: RawAxiosRequestConfig) {
        return ModelServiceApiFp(this.configuration).modelServiceCreateModel(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelServiceApiModelServiceDeleteModelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelServiceApi
     */
    public modelServiceDeleteModel(requestParameters: ModelServiceApiModelServiceDeleteModelRequest, options?: RawAxiosRequestConfig) {
        return ModelServiceApiFp(this.configuration).modelServiceDeleteModel(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelServiceApiModelServiceGetModelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelServiceApi
     */
    public modelServiceGetModel(requestParameters: ModelServiceApiModelServiceGetModelRequest, options?: RawAxiosRequestConfig) {
        return ModelServiceApiFp(this.configuration).modelServiceGetModel(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelServiceApiModelServiceListModelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelServiceApi
     */
    public modelServiceListModel(requestParameters: ModelServiceApiModelServiceListModelRequest = {}, options?: RawAxiosRequestConfig) {
        return ModelServiceApiFp(this.configuration).modelServiceListModel(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, requestParameters.filterInternal$eq, requestParameters.filterInternal$neq, requestParameters.filterInternal$null, requestParameters.filterInternal$nnull, requestParameters.afterPageToken, requestParameters.beforePageToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelServiceApiModelServiceListModel2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelServiceApi
     */
    public modelServiceListModel2(requestParameters: ModelServiceApiModelServiceListModel2Request, options?: RawAxiosRequestConfig) {
        return ModelServiceApiFp(this.configuration).modelServiceListModel2(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelServiceApiModelServiceUpdateModelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelServiceApi
     */
    public modelServiceUpdateModel(requestParameters: ModelServiceApiModelServiceUpdateModelRequest, options?: RawAxiosRequestConfig) {
        return ModelServiceApiFp(this.configuration).modelServiceUpdateModel(requestParameters.modelId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ModelServiceApiModelServiceUpdateModel2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelServiceApi
     */
    public modelServiceUpdateModel2(requestParameters: ModelServiceApiModelServiceUpdateModel2Request, options?: RawAxiosRequestConfig) {
        return ModelServiceApiFp(this.configuration).modelServiceUpdateModel2(requestParameters.modelId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}

