/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GooglerpcStatus } from '../models';
// @ts-ignore
import type { V1GetPaymentMethodReply } from '../models';
/**
 * PaymentGatewayServiceApi - axios parameter creator
 * @export
 */
export const PaymentGatewayServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [orderId] 
         * @param {boolean} [isTest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentGatewayServiceGetPaymentMethod: async (orderId?: string, isTest?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/payment/methods`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (orderId !== undefined) {
                localVarQueryParameter['orderId'] = orderId;
            }

            if (isTest !== undefined) {
                localVarQueryParameter['isTest'] = isTest;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentGatewayServiceApi - functional programming interface
 * @export
 */
export const PaymentGatewayServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentGatewayServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [orderId] 
         * @param {boolean} [isTest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentGatewayServiceGetPaymentMethod(orderId?: string, isTest?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1GetPaymentMethodReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentGatewayServiceGetPaymentMethod(orderId, isTest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentGatewayServiceApi.paymentGatewayServiceGetPaymentMethod']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaymentGatewayServiceApi - factory interface
 * @export
 */
export const PaymentGatewayServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentGatewayServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {PaymentGatewayServiceApiPaymentGatewayServiceGetPaymentMethodRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentGatewayServiceGetPaymentMethod(requestParameters: PaymentGatewayServiceApiPaymentGatewayServiceGetPaymentMethodRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<V1GetPaymentMethodReply> {
            return localVarFp.paymentGatewayServiceGetPaymentMethod(requestParameters.orderId, requestParameters.isTest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for paymentGatewayServiceGetPaymentMethod operation in PaymentGatewayServiceApi.
 * @export
 * @interface PaymentGatewayServiceApiPaymentGatewayServiceGetPaymentMethodRequest
 */
export interface PaymentGatewayServiceApiPaymentGatewayServiceGetPaymentMethodRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentGatewayServiceApiPaymentGatewayServiceGetPaymentMethod
     */
    readonly orderId?: string

    /**
     * 
     * @type {boolean}
     * @memberof PaymentGatewayServiceApiPaymentGatewayServiceGetPaymentMethod
     */
    readonly isTest?: boolean
}

/**
 * PaymentGatewayServiceApi - object-oriented interface
 * @export
 * @class PaymentGatewayServiceApi
 * @extends {BaseAPI}
 */
export class PaymentGatewayServiceApi extends BaseAPI {
    /**
     * 
     * @param {PaymentGatewayServiceApiPaymentGatewayServiceGetPaymentMethodRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentGatewayServiceApi
     */
    public paymentGatewayServiceGetPaymentMethod(requestParameters: PaymentGatewayServiceApiPaymentGatewayServiceGetPaymentMethodRequest = {}, options?: RawAxiosRequestConfig) {
        return PaymentGatewayServiceApiFp(this.configuration).paymentGatewayServiceGetPaymentMethod(requestParameters.orderId, requestParameters.isTest, options).then((request) => request(this.axios, this.basePath));
    }
}

