/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ARTExplainerSpecARTExplainerType = {
    Unspecified: 'ART_EXPLAINER_TYPE_UNSPECIFIED',
    SquareAttack: 'ART_EXPLAINER_TYPE_SQUARE_ATTACK'
} as const;

export type ARTExplainerSpecARTExplainerType = typeof ARTExplainerSpecARTExplainerType[keyof typeof ARTExplainerSpecARTExplainerType];



