/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlobBlobFile
 */
export interface BlobBlobFile {
    /**
     * 
     * @type {string}
     * @memberof BlobBlobFile
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlobBlobFile
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlobBlobFile
     */
    'mime'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlobBlobFile
     */
    'size'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlobBlobFile
     */
    'url'?: string;
    /**
     * 
     * @type {object}
     * @memberof BlobBlobFile
     */
    'metadata'?: object;
}

