/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CheckoutServiceCheckoutOrderRequest
 */
export interface CheckoutServiceCheckoutOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof CheckoutServiceCheckoutOrderRequest
     */
    'provider': string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutServiceCheckoutOrderRequest
     */
    'currencyCode'?: string;
}

