/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ClientOAuth2Client } from './client-oauth2-client';

/**
 * 
 * @export
 * @interface ClientServiceUpdateOAuth2ClientRequest
 */
export interface ClientServiceUpdateOAuth2ClientRequest {
    /**
     * 
     * @type {ClientOAuth2Client}
     * @memberof ClientServiceUpdateOAuth2ClientRequest
     */
    'client'?: ClientOAuth2Client;
}

