/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClientPatchOAuth2Client
 */
export interface ClientPatchOAuth2Client {
    /**
     * 
     * @type {string}
     * @memberof ClientPatchOAuth2Client
     */
    'from'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientPatchOAuth2Client
     */
    'op'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPatchOAuth2Client
     */
    'path'?: string;
    /**
     * 
     * @type {object}
     * @memberof ClientPatchOAuth2Client
     */
    'value'?: object;
}

