/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ClientPatchOAuth2Client } from './client-patch-oauth2-client';

/**
 * 
 * @export
 * @interface ClientServicePatchOAuth2ClientRequest
 */
export interface ClientServicePatchOAuth2ClientRequest {
    /**
     * 
     * @type {Array<ClientPatchOAuth2Client>}
     * @memberof ClientServicePatchOAuth2ClientRequest
     */
    'client'?: Array<ClientPatchOAuth2Client>;
}

