/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ComponentExtensionSpecScaleMetric = {
    Unspecified: 'SCALE_METRIC_UNSPECIFIED',
    Cpu: 'SCALE_METRIC_CPU',
    Memory: 'SCALE_METRIC_MEMORY',
    Concurrency: 'SCALE_METRIC_CONCURRENCY',
    Rps: 'SCALE_METRIC_RPS'
} as const;

export type ComponentExtensionSpecScaleMetric = typeof ComponentExtensionSpecScaleMetric[keyof typeof ComponentExtensionSpecScaleMetric];



