/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DataDynamicValue
 */
export interface DataDynamicValue {
    /**
     * 
     * @type {number}
     * @memberof DataDynamicValue
     */
    'intValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof DataDynamicValue
     */
    'longValue'?: string;
    /**
     * 
     * @type {number}
     * @memberof DataDynamicValue
     */
    'floatValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof DataDynamicValue
     */
    'doubleValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof DataDynamicValue
     */
    'stringValue'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DataDynamicValue
     */
    'boolValue'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DataDynamicValue
     */
    'nullValue'?: string;
    /**
     * 
     * @type {object}
     * @memberof DataDynamicValue
     */
    'jsonValue'?: object;
}

