/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const FailureInfoFailureReason = {
    Unspecified: 'FAILURE_REASON_UNSPECIFIED',
    ModelLoadFailed: 'FAILURE_REASON_MODEL_LOAD_FAILED',
    NoSupportingRuntime: 'FAILURE_REASON_NO_SUPPORTING_RUNTIME',
    RuntimeDisabled: 'FAILURE_REASON_RUNTIME_DISABLED',
    RuntimeNotRecognized: 'FAILURE_REASON_RUNTIME_NOT_RECOGNIZED',
    RuntimeUnhealthy: 'FAILURE_REASON_RUNTIME_UNHEALTHY'
} as const;

export type FailureInfoFailureReason = typeof FailureInfoFailureReason[keyof typeof FailureInfoFailureReason];



