/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeyJsonWebKeySetGeneratorRequest
 */
export interface KeyJsonWebKeySetGeneratorRequest {
    /**
     * 
     * @type {string}
     * @memberof KeyJsonWebKeySetGeneratorRequest
     */
    'alg': string;
    /**
     * 
     * @type {string}
     * @memberof KeyJsonWebKeySetGeneratorRequest
     */
    'kid': string;
    /**
     * 
     * @type {string}
     * @memberof KeyJsonWebKeySetGeneratorRequest
     */
    'use': string;
}

