/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const LoggerSpecLoggerType = {
    Unspecified: 'LOGGER_TYPE_UNSPECIFIED',
    All: 'LOGGER_TYPE_ALL',
    Request: 'LOGGER_TYPE_REQUEST',
    Response: 'LOGGER_TYPE_RESPONSE'
} as const;

export type LoggerSpecLoggerType = typeof LoggerSpecLoggerType[keyof typeof LoggerSpecLoggerType];



