/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MenuServiceUpdateMenuRequestMenu } from './menu-service-update-menu-request-menu';

/**
 * 
 * @export
 * @interface MenuServiceUpdateMenuRequest
 */
export interface MenuServiceUpdateMenuRequest {
    /**
     * 
     * @type {MenuServiceUpdateMenuRequestMenu}
     * @memberof MenuServiceUpdateMenuRequest
     */
    'menu'?: MenuServiceUpdateMenuRequestMenu;
    /**
     * 
     * @type {string}
     * @memberof MenuServiceUpdateMenuRequest
     */
    'updateMask'?: string;
}

