/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - TRANSITION_STATUS_BLOCKED_BY_FAILED_LOAD: Target model failed to load  - TRANSITION_STATUS_IN_PROGRESS: Waiting for the target model to be ready  - TRANSITION_STATUS_INVALID_SPEC: Target predictor spec failed validation  - TRANSITION_STATUS_UP_TO_DATE: Target predictor spec is up to date
 * @export
 * @enum {string}
 */

export const ModelStatusTransitionStatus = {
    Unspecified: 'TRANSITION_STATUS_UNSPECIFIED',
    BlockedByFailedLoad: 'TRANSITION_STATUS_BLOCKED_BY_FAILED_LOAD',
    InProgress: 'TRANSITION_STATUS_IN_PROGRESS',
    InvalidSpec: 'TRANSITION_STATUS_INVALID_SPEC',
    UpToDate: 'TRANSITION_STATUS_UP_TO_DATE'
} as const;

export type ModelStatusTransitionStatus = typeof ModelStatusTransitionStatus[keyof typeof ModelStatusTransitionStatus];



