/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelVersionMetadata } from './v1beta1-model-version-metadata';

/**
 * 
 * @export
 * @interface ModelVersionServiceUpdateVersionRequestVersion
 */
export interface ModelVersionServiceUpdateVersionRequestVersion {
    /**
     * 
     * @type {string}
     * @memberof ModelVersionServiceUpdateVersionRequestVersion
     */
    'name'?: string;
    /**
     * 
     * @type {V1beta1ModelVersionMetadata}
     * @memberof ModelVersionServiceUpdateVersionRequestVersion
     */
    'metadata'?: V1beta1ModelVersionMetadata;
}

