/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelRevisionStatesModelState } from './model-revision-states-model-state';

/**
 * State information of the predictor’s model.
 * @export
 * @interface ModelStatusModelRevisionStates
 */
export interface ModelStatusModelRevisionStates {
    /**
     * 
     * @type {ModelRevisionStatesModelState}
     * @memberof ModelStatusModelRevisionStates
     */
    'activeModelState'?: ModelRevisionStatesModelState;
    /**
     * 
     * @type {ModelRevisionStatesModelState}
     * @memberof ModelStatusModelRevisionStates
     */
    'targetModelState'?: ModelRevisionStatesModelState;
}



