/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ModelRevisionStatesModelState = {
    Unspecified: 'MODEL_STATE_UNSPECIFIED',
    Pending: 'MODEL_STATE_PENDING',
    Loading: 'MODEL_STATE_LOADING',
    Loaded: 'MODEL_STATE_LOADED',
    FailedToLoad: 'MODEL_STATE_FAILED_TO_LOAD',
    Standby: 'MODEL_STATE_STANDBY'
} as const;

export type ModelRevisionStatesModelState = typeof ModelRevisionStatesModelState[keyof typeof ModelRevisionStatesModelState];



