/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FailureInfoFailureReason } from './failure-info-failure-reason';

/**
 * Details of last failure, when load of target model is failed or blocked.
 * @export
 * @interface ModelStatusFailureInfo
 */
export interface ModelStatusFailureInfo {
    /**
     * 
     * @type {string}
     * @memberof ModelStatusFailureInfo
     */
    'location'?: string | null;
    /**
     * 
     * @type {FailureInfoFailureReason}
     * @memberof ModelStatusFailureInfo
     */
    'failureReason'?: FailureInfoFailureReason;
    /**
     * 
     * @type {string}
     * @memberof ModelStatusFailureInfo
     */
    'message'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModelStatusFailureInfo
     */
    'modelRevisionName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModelStatusFailureInfo
     */
    'lastUpdateTimestamp'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ModelStatusFailureInfo
     */
    'exitCode'?: number | null;
}



