/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelServiceUpdateModelRequestModel } from './model-service-update-model-request-model';

/**
 * 
 * @export
 * @interface ModelServiceUpdateModelRequest
 */
export interface ModelServiceUpdateModelRequest {
    /**
     * 
     * @type {ModelServiceUpdateModelRequestModel}
     * @memberof ModelServiceUpdateModelRequest
     */
    'model'?: ModelServiceUpdateModelRequestModel;
    /**
     * 
     * @type {string}
     * @memberof ModelServiceUpdateModelRequest
     */
    'updateMask'?: string;
}

