/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model copy information of the predictor’s model.
 * @export
 * @interface ModelStatusModelCopies
 */
export interface ModelStatusModelCopies {
    /**
     * 
     * @type {number}
     * @memberof ModelStatusModelCopies
     */
    'failedCopyCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelStatusModelCopies
     */
    'totalCopyCount'?: number | null;
}

