/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OperationBooleanFilterOperators
 */
export interface OperationBooleanFilterOperators {
    /**
     * 
     * @type {boolean}
     * @memberof OperationBooleanFilterOperators
     */
    '$eq'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OperationBooleanFilterOperators
     */
    '$neq'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OperationBooleanFilterOperators
     */
    '$null'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OperationBooleanFilterOperators
     */
    '$nnull'?: boolean | null;
}

