/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OperationDateFilterOperators
 */
export interface OperationDateFilterOperators {
    /**
     * 
     * @type {string}
     * @memberof OperationDateFilterOperators
     */
    '$eq'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OperationDateFilterOperators
     */
    '$neq'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OperationDateFilterOperators
     */
    '$gt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OperationDateFilterOperators
     */
    '$gte'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OperationDateFilterOperators
     */
    '$lt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OperationDateFilterOperators
     */
    '$lte'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OperationDateFilterOperators
     */
    '$null'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OperationDateFilterOperators
     */
    '$nnull'?: boolean | null;
}

