/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Permissionv1PermissionDef } from './permissionv1-permission-def';
// May contain unused imports in some cases
// @ts-ignore
import type { V1PermissionSide } from './v1-permission-side';

/**
 * 
 * @export
 * @interface Permissionv1PermissionDefGroup
 */
export interface Permissionv1PermissionDefGroup {
    /**
     * 
     * @type {string}
     * @memberof Permissionv1PermissionDefGroup
     */
    'displayName'?: string;
    /**
     * 
     * @type {V1PermissionSide}
     * @memberof Permissionv1PermissionDefGroup
     */
    'side'?: V1PermissionSide;
    /**
     * 
     * @type {number}
     * @memberof Permissionv1PermissionDefGroup
     */
    'priority'?: number;
    /**
     * 
     * @type {Array<Permissionv1PermissionDef>}
     * @memberof Permissionv1PermissionDefGroup
     */
    'def'?: Array<Permissionv1PermissionDef>;
    /**
     * 
     * @type {object}
     * @memberof Permissionv1PermissionDefGroup
     */
    'extra'?: object;
    /**
     * 
     * @type {string}
     * @memberof Permissionv1PermissionDefGroup
     */
    'name'?: string;
}



