/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PlanServiceUpdatePlanRequestPlan } from './plan-service-update-plan-request-plan';

/**
 * 
 * @export
 * @interface PlanServiceUpdatePlanRequest
 */
export interface PlanServiceUpdatePlanRequest {
    /**
     * 
     * @type {PlanServiceUpdatePlanRequestPlan}
     * @memberof PlanServiceUpdatePlanRequest
     */
    'plan'?: PlanServiceUpdatePlanRequestPlan;
    /**
     * 
     * @type {string}
     * @memberof PlanServiceUpdatePlanRequest
     */
    'updateMask'?: string;
}

