/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const PredictorExtensionSpecInferenceServiceProtocol = {
    Unspecified: 'INFERENCE_SERVICE_PROTOCOL_UNSPECIFIED',
    HttpV1: 'INFERENCE_SERVICE_PROTOCOL_HTTP_V1',
    HttpV2: 'INFERENCE_SERVICE_PROTOCOL_HTTP_V2',
    GrpcV1: 'INFERENCE_SERVICE_PROTOCOL_GRPC_V1',
    GrpcV2: 'INFERENCE_SERVICE_PROTOCOL_GRPC_V2'
} as const;

export type PredictorExtensionSpecInferenceServiceProtocol = typeof PredictorExtensionSpecInferenceServiceProtocol[keyof typeof PredictorExtensionSpecInferenceServiceProtocol];



