/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PricePricePb
 */
export interface PricePricePb {
    /**
     * 
     * @type {string}
     * @memberof PricePricePb
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricePricePb
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof PricePricePb
     */
    'digits'?: number;
    /**
     * 
     * @type {string}
     * @memberof PricePricePb
     */
    'text'?: string;
    /**
     * 
     * @type {string}
     * @memberof PricePricePb
     */
    'amountDecimal'?: string;
}

