/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1UpdateRolePermissionAcl } from './v1-update-role-permission-acl';

/**
 * 
 * @export
 * @interface RoleServiceUpdateRolePermissionRequest
 */
export interface RoleServiceUpdateRolePermissionRequest {
    /**
     * 
     * @type {Array<V1UpdateRolePermissionAcl>}
     * @memberof RoleServiceUpdateRolePermissionRequest
     */
    'acl'?: Array<V1UpdateRolePermissionAcl>;
}

