/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StripePaymentIntent } from './stripe-payment-intent';

/**
 * 
 * @export
 * @interface StripeInvoice
 */
export interface StripeInvoice {
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    'id'?: string;
    /**
     * 
     * @type {StripePaymentIntent}
     * @memberof StripeInvoice
     */
    'paymentIntent'?: StripePaymentIntent;
}

