/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StripePaymentIntent
 */
export interface StripePaymentIntent {
    /**
     * 
     * @type {string}
     * @memberof StripePaymentIntent
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof StripePaymentIntent
     */
    'clientSecret'?: string;
    /**
     * 
     * @type {string}
     * @memberof StripePaymentIntent
     */
    'status'?: string;
}

