/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubscriptionServiceUpdateMySubscriptionRequest
 */
export interface SubscriptionServiceUpdateMySubscriptionRequest {
    /**
     * 
     * @type {object}
     * @memberof SubscriptionServiceUpdateMySubscriptionRequest
     */
    'subscription'?: object;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionServiceUpdateMySubscriptionRequest
     */
    'updateMask'?: string;
}

