/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1SubscriptionItem } from './v1-subscription-item';
// May contain unused imports in some cases
// @ts-ignore
import type { V1SubscriptionProviderInfo } from './v1-subscription-provider-info';
// May contain unused imports in some cases
// @ts-ignore
import type { V1User } from './v1-user';

/**
 * 
 * @export
 * @interface Subscriptionv1Subscription
 */
export interface Subscriptionv1Subscription {
    /**
     * 
     * @type {string}
     * @memberof Subscriptionv1Subscription
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscriptionv1Subscription
     */
    'userId'?: string;
    /**
     * 
     * @type {V1User}
     * @memberof Subscriptionv1Subscription
     */
    'user'?: V1User;
    /**
     * 
     * @type {string}
     * @memberof Subscriptionv1Subscription
     */
    'provider'?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscriptionv1Subscription
     */
    'providerKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscriptionv1Subscription
     */
    'status'?: string;
    /**
     * 
     * @type {Array<V1SubscriptionItem>}
     * @memberof Subscriptionv1Subscription
     */
    'items'?: Array<V1SubscriptionItem>;
    /**
     * 
     * @type {V1SubscriptionProviderInfo}
     * @memberof Subscriptionv1Subscription
     */
    'providerInfo'?: V1SubscriptionProviderInfo;
}

