/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TenantServiceUpdateTenantRequestTenant } from './tenant-service-update-tenant-request-tenant';

/**
 * 
 * @export
 * @interface TenantServiceUpdateTenantRequest
 */
export interface TenantServiceUpdateTenantRequest {
    /**
     * 
     * @type {TenantServiceUpdateTenantRequestTenant}
     * @memberof TenantServiceUpdateTenantRequest
     */
    'tenant'?: TenantServiceUpdateTenantRequestTenant;
    /**
     * 
     * @type {string}
     * @memberof TenantServiceUpdateTenantRequest
     */
    'updateMask'?: string;
}

