/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserAdminServiceUpdateUserAdminRequestUser } from './user-admin-service-update-user-admin-request-user';

/**
 * 
 * @export
 * @interface UserAdminServiceUpdateUserAdminRequest
 */
export interface UserAdminServiceUpdateUserAdminRequest {
    /**
     * 
     * @type {UserAdminServiceUpdateUserAdminRequestUser}
     * @memberof UserAdminServiceUpdateUserAdminRequest
     */
    'user'?: UserAdminServiceUpdateUserAdminRequestUser;
    /**
     * 
     * @type {string}
     * @memberof UserAdminServiceUpdateUserAdminRequest
     */
    'updateMask'?: string;
}

