/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1CreateBrandRequest
 */
export interface V1CreateBrandRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateBrandRequest
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateBrandRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateBrandRequest
     */
    'logo'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateBrandRequest
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateBrandRequest
     */
    'desc'?: string;
}

