/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1SubscriptionItemParams } from './v1-subscription-item-params';

/**
 * 
 * @export
 * @interface V1CreateSubscriptionRequest
 */
export interface V1CreateSubscriptionRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateSubscriptionRequest
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateSubscriptionRequest
     */
    'provider'?: string;
    /**
     * 
     * @type {Array<V1SubscriptionItemParams>}
     * @memberof V1CreateSubscriptionRequest
     */
    'items'?: Array<V1SubscriptionItemParams>;
}

