/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1OrderProduct } from './v1-order-product';

/**
 * 
 * @export
 * @interface V1CreateInternalOrderItem
 */
export interface V1CreateInternalOrderItem {
    /**
     * 
     * @type {string}
     * @memberof V1CreateInternalOrderItem
     */
    'qty'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateInternalOrderItem
     */
    'priceAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateInternalOrderItem
     */
    'originalPriceAmount'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1CreateInternalOrderItem
     */
    'isGiveaway'?: boolean;
    /**
     * 
     * @type {V1OrderProduct}
     * @memberof V1CreateInternalOrderItem
     */
    'product': V1OrderProduct;
    /**
     * 
     * @type {object}
     * @memberof V1CreateInternalOrderItem
     */
    'bizPayload'?: object;
}

