/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1ChangePasswordByForgetRequest
 */
export interface V1ChangePasswordByForgetRequest {
    /**
     * 
     * @type {string}
     * @memberof V1ChangePasswordByForgetRequest
     */
    'changePasswordToken': string;
    /**
     * 
     * @type {string}
     * @memberof V1ChangePasswordByForgetRequest
     */
    'newPassword': string;
    /**
     * 
     * @type {string}
     * @memberof V1ChangePasswordByForgetRequest
     */
    'confirmNewPassword': string;
}

