/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1OrderPaymentProviderInfo } from './v1-order-payment-provider-info';

/**
 * 
 * @export
 * @interface V1CheckoutOrderReply
 */
export interface V1CheckoutOrderReply {
    /**
     * 
     * @type {V1OrderPaymentProviderInfo}
     * @memberof V1CheckoutOrderReply
     */
    'paymentProviderInfo'?: V1OrderPaymentProviderInfo;
}

