/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1CheckoutItemParams } from './v1-checkout-item-params';

/**
 * 
 * @export
 * @interface V1CheckoutNowRequest
 */
export interface V1CheckoutNowRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutNowRequest
     */
    'provider': string;
    /**
     * 
     * @type {string}
     * @memberof V1CheckoutNowRequest
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {Array<V1CheckoutItemParams>}
     * @memberof V1CheckoutNowRequest
     */
    'items'?: Array<V1CheckoutItemParams>;
}

