/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Subscriptionv1Subscription } from './subscriptionv1-subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { V1Order } from './v1-order';

/**
 * 
 * @export
 * @interface V1CheckoutNowReply
 */
export interface V1CheckoutNowReply {
    /**
     * 
     * @type {Subscriptionv1Subscription}
     * @memberof V1CheckoutNowReply
     */
    'subscription'?: Subscriptionv1Subscription;
    /**
     * 
     * @type {V1Order}
     * @memberof V1CheckoutNowReply
     */
    'order'?: V1Order;
}

