/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V1Effect = {
    Unknown: 'UNKNOWN',
    Grant: 'GRANT',
    Forbidden: 'FORBIDDEN'
} as const;

export type V1Effect = typeof V1Effect[keyof typeof V1Effect];



