/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1ForgetPasswordTokenRequest
 */
export interface V1ForgetPasswordTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof V1ForgetPasswordTokenRequest
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1ForgetPasswordTokenRequest
     */
    'email'?: string | null;
}

