/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V1Gender = {
    Unknown: 'UNKNOWN',
    Male: 'MALE',
    Female: 'FEMALE',
    Other: 'OTHER'
} as const;

export type V1Gender = typeof V1Gender[keyof typeof V1Gender];



