/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1GetStripeConfigReply
 */
export interface V1GetStripeConfigReply {
    /**
     * 
     * @type {boolean}
     * @memberof V1GetStripeConfigReply
     */
    'isTest'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1GetStripeConfigReply
     */
    'publishKey'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof V1GetStripeConfigReply
     */
    'priceTables'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof V1GetStripeConfigReply
     */
    'customerId'?: string;
}

