/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1PaymentMethod } from './v1-payment-method';

/**
 * 
 * @export
 * @interface V1GetPaymentMethodReply
 */
export interface V1GetPaymentMethodReply {
    /**
     * 
     * @type {Array<V1PaymentMethod>}
     * @memberof V1GetPaymentMethodReply
     */
    'methods'?: Array<V1PaymentMethod>;
}

