/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Permissionv1PermissionDefGroup } from './permissionv1-permission-def-group';
// May contain unused imports in some cases
// @ts-ignore
import type { V1Permission } from './v1-permission';

/**
 * 
 * @export
 * @interface V1GetRolePermissionResponse
 */
export interface V1GetRolePermissionResponse {
    /**
     * 
     * @type {Array<V1Permission>}
     * @memberof V1GetRolePermissionResponse
     */
    'acl'?: Array<V1Permission>;
    /**
     * 
     * @type {Array<Permissionv1PermissionDefGroup>}
     * @memberof V1GetRolePermissionResponse
     */
    'defGroups'?: Array<Permissionv1PermissionDefGroup>;
}

