/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1OAuthProvider } from './v1-oauth-provider';

/**
 * 
 * @export
 * @interface V1GetLoginResponse
 */
export interface V1GetLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof V1GetLoginResponse
     */
    'redirect'?: string;
    /**
     * 
     * @type {Array<V1OAuthProvider>}
     * @memberof V1GetLoginResponse
     */
    'oauth'?: Array<V1OAuthProvider>;
    /**
     * 
     * @type {string}
     * @memberof V1GetLoginResponse
     */
    'hint'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetLoginResponse
     */
    'challenge'?: string;
}

