/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1UserAddress } from './v1-user-address';

/**
 * 
 * @export
 * @interface V1GetAddressesReply
 */
export interface V1GetAddressesReply {
    /**
     * 
     * @type {Array<V1UserAddress>}
     * @memberof V1GetAddressesReply
     */
    'addresses'?: Array<V1UserAddress>;
}

