/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Subscriptionv1Subscription } from './subscriptionv1-subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { V1Plan } from './v1-plan';

/**
 * 
 * @export
 * @interface V1GetAvailablePlansReply
 */
export interface V1GetAvailablePlansReply {
    /**
     * 
     * @type {Array<V1Plan>}
     * @memberof V1GetAvailablePlansReply
     */
    'items'?: Array<V1Plan>;
    /**
     * 
     * @type {Subscriptionv1Subscription}
     * @memberof V1GetAvailablePlansReply
     */
    'activeSubscription'?: Subscriptionv1Subscription;
}

