/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1GrantConsentRequest
 */
export interface V1GrantConsentRequest {
    /**
     * 
     * @type {string}
     * @memberof V1GrantConsentRequest
     */
    'challenge'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1GrantConsentRequest
     */
    'grantScope'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof V1GrantConsentRequest
     */
    'reject'?: boolean;
}

