/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1Order } from './v1-order';

/**
 * 
 * @export
 * @interface V1ListOrderReply
 */
export interface V1ListOrderReply {
    /**
     * 
     * @type {number}
     * @memberof V1ListOrderReply
     */
    'totalSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListOrderReply
     */
    'filterSize'?: number;
    /**
     * 
     * @type {Array<V1Order>}
     * @memberof V1ListOrderReply
     */
    'items'?: Array<V1Order>;
    /**
     * 
     * @type {string}
     * @memberof V1ListOrderReply
     */
    'nextAfterPageToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1ListOrderReply
     */
    'nextBeforePageToken'?: string | null;
}

