/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1LocaleLanguage } from './v1-locale-language';

/**
 * 
 * @export
 * @interface V1ListMessageReply
 */
export interface V1ListMessageReply {
    /**
     * 
     * @type {Array<V1LocaleLanguage>}
     * @memberof V1ListMessageReply
     */
    'items'?: Array<V1LocaleLanguage>;
}

