/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1LocaleMessage } from './v1-locale-message';

/**
 * 
 * @export
 * @interface V1LocaleLanguage
 */
export interface V1LocaleLanguage {
    /**
     * 
     * @type {string}
     * @memberof V1LocaleLanguage
     */
    'name'?: string;
    /**
     * 
     * @type {Array<V1LocaleMessage>}
     * @memberof V1LocaleLanguage
     */
    'msg'?: Array<V1LocaleMessage>;
}

