/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1ProductCategory } from './v1-product-category';

/**
 * 
 * @export
 * @interface V1ListProductCategoryReply
 */
export interface V1ListProductCategoryReply {
    /**
     * 
     * @type {number}
     * @memberof V1ListProductCategoryReply
     */
    'totalSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListProductCategoryReply
     */
    'filterSize'?: number;
    /**
     * 
     * @type {Array<V1ProductCategory>}
     * @memberof V1ListProductCategoryReply
     */
    'items'?: Array<V1ProductCategory>;
}

