/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1LoginPasswordlessReply
 */
export interface V1LoginPasswordlessReply {
    /**
     * 
     * @type {string}
     * @memberof V1LoginPasswordlessReply
     */
    'accessToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1LoginPasswordlessReply
     */
    'tokenType'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1LoginPasswordlessReply
     */
    'refreshToken'?: string;
    /**
     * 
     * @type {number}
     * @memberof V1LoginPasswordlessReply
     */
    'expiresIn'?: number;
}

