/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1RoleFilter } from './v1-role-filter';

/**
 * 
 * @export
 * @interface V1ListRolesRequest
 */
export interface V1ListRolesRequest {
    /**
     * 
     * @type {number}
     * @memberof V1ListRolesRequest
     */
    'pageOffset'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListRolesRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof V1ListRolesRequest
     */
    'search'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1ListRolesRequest
     */
    'sort'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1ListRolesRequest
     */
    'fields'?: string;
    /**
     * 
     * @type {V1RoleFilter}
     * @memberof V1ListRolesRequest
     */
    'filter'?: V1RoleFilter;
}

