/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1NotificationFilter } from './v1-notification-filter';

/**
 * 
 * @export
 * @interface V1ListNotificationRequest
 */
export interface V1ListNotificationRequest {
    /**
     * 
     * @type {string}
     * @memberof V1ListNotificationRequest
     */
    'afterPageToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ListNotificationRequest
     */
    'beforePageToken'?: string;
    /**
     * 
     * @type {number}
     * @memberof V1ListNotificationRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1ListNotificationRequest
     */
    'sort'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1ListNotificationRequest
     */
    'fields'?: string;
    /**
     * 
     * @type {V1NotificationFilter}
     * @memberof V1ListNotificationRequest
     */
    'filter'?: V1NotificationFilter;
}

