/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1MessageProto
 */
export interface V1MessageProto {
    /**
     * 
     * @type {string}
     * @memberof V1MessageProto
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1MessageProto
     */
    'value'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof V1MessageProto
     */
    'header'?: { [key: string]: string; };
}

