/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1OrderProduct
 */
export interface V1OrderProduct {
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'mainPic'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'skuId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'skuTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'priceId'?: string | null;
}

