/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1OrderPaymentStripeInfo } from './v1-order-payment-stripe-info';

/**
 * 
 * @export
 * @interface V1OrderPaymentProviderInfo
 */
export interface V1OrderPaymentProviderInfo {
    /**
     * 
     * @type {V1OrderPaymentStripeInfo}
     * @memberof V1OrderPaymentProviderInfo
     */
    'stripe'?: V1OrderPaymentStripeInfo;
}

