/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1OAuthClient
 */
export interface V1OAuthClient {
    /**
     * 
     * @type {string}
     * @memberof V1OAuthClient
     */
    'clientId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1OAuthClient
     */
    'clientName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1OAuthClient
     */
    'clientUri'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1OAuthClient
     */
    'contacts'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1OAuthClient
     */
    'logoUri'?: string | null;
    /**
     * 
     * @type {object}
     * @memberof V1OAuthClient
     */
    'metadata'?: object | null;
    /**
     * 
     * @type {string}
     * @memberof V1OAuthClient
     */
    'owner'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1OAuthClient
     */
    'policyUri'?: string | null;
}

