/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PricePricePb } from './price-price-pb';
// May contain unused imports in some cases
// @ts-ignore
import type { V1PriceCurrencyOptionTier } from './v1-price-currency-option-tier';

/**
 * 
 * @export
 * @interface V1PriceCurrencyOption
 */
export interface V1PriceCurrencyOption {
    /**
     * 
     * @type {string}
     * @memberof V1PriceCurrencyOption
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1PriceCurrencyOption
     */
    'default'?: PricePricePb;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1PriceCurrencyOption
     */
    'discounted'?: PricePricePb;
    /**
     * 
     * @type {string}
     * @memberof V1PriceCurrencyOption
     */
    'discountText'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1PriceCurrencyOption
     */
    'denyMoreDiscounts'?: boolean;
    /**
     * 
     * @type {Array<V1PriceCurrencyOptionTier>}
     * @memberof V1PriceCurrencyOption
     */
    'tiers'?: Array<V1PriceCurrencyOptionTier>;
}

