/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1PriceRecurring
 */
export interface V1PriceRecurring {
    /**
     * 
     * @type {string}
     * @memberof V1PriceRecurring
     */
    'interval': string;
    /**
     * 
     * @type {string}
     * @memberof V1PriceRecurring
     */
    'intervalCount'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PriceRecurring
     */
    'trialPeriodDays'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PriceRecurring
     */
    'aggregateUsage'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PriceRecurring
     */
    'usageType'?: string;
}

