/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V1PermissionSide = {
    Both: 'BOTH',
    HostOnly: 'HOST_ONLY',
    TenantOnly: 'TENANT_ONLY'
} as const;

export type V1PermissionSide = typeof V1PermissionSide[keyof typeof V1PermissionSide];



