/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1PriceCurrencyOptionTierParams
 */
export interface V1PriceCurrencyOptionTierParams {
    /**
     * 
     * @type {string}
     * @memberof V1PriceCurrencyOptionTierParams
     */
    'flatAmountDecimal'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PriceCurrencyOptionTierParams
     */
    'unitAmountDecimal'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PriceCurrencyOptionTierParams
     */
    'upTo'?: string;
}

