/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1ProductMedia
 */
export interface V1ProductMedia {
    /**
     * 
     * @type {string}
     * @memberof V1ProductMedia
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProductMedia
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProductMedia
     */
    'mimeType'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProductMedia
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProductMedia
     */
    'url'?: string;
}

