/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OperationBooleanFilterOperators } from './operation-boolean-filter-operators';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationStringFilterOperation } from './operation-string-filter-operation';

/**
 * 
 * @export
 * @interface V1PlanFilter
 */
export interface V1PlanFilter {
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1PlanFilter
     */
    'key'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1PlanFilter
     */
    'displayName'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationBooleanFilterOperators}
     * @memberof V1PlanFilter
     */
    'active'?: OperationBooleanFilterOperators;
}

