/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1PriceCurrencyOptionParams } from './v1-price-currency-option-params';
// May contain unused imports in some cases
// @ts-ignore
import type { V1PriceRecurring } from './v1-price-recurring';
// May contain unused imports in some cases
// @ts-ignore
import type { V1PriceTierParams } from './v1-price-tier-params';
// May contain unused imports in some cases
// @ts-ignore
import type { V1PriceTransformQuantity } from './v1-price-transform-quantity';

/**
 * 
 * @export
 * @interface V1PriceParams
 */
export interface V1PriceParams {
    /**
     * 
     * @type {string}
     * @memberof V1PriceParams
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PriceParams
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PriceParams
     */
    'defaultAmountDecimal'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PriceParams
     */
    'discountedAmountDecimal'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1PriceParams
     */
    'discountText'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1PriceParams
     */
    'denyMoreDiscounts'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1PriceParams
     */
    'billingScheme': string;
    /**
     * 
     * @type {Array<V1PriceCurrencyOptionParams>}
     * @memberof V1PriceParams
     */
    'currencyOptions'?: Array<V1PriceCurrencyOptionParams>;
    /**
     * 
     * @type {V1PriceRecurring}
     * @memberof V1PriceParams
     */
    'recurring'?: V1PriceRecurring;
    /**
     * 
     * @type {Array<V1PriceTierParams>}
     * @memberof V1PriceParams
     */
    'tiers'?: Array<V1PriceTierParams>;
    /**
     * 
     * @type {string}
     * @memberof V1PriceParams
     */
    'tiersMode'?: string;
    /**
     * 
     * @type {V1PriceTransformQuantity}
     * @memberof V1PriceParams
     */
    'transformQuantity'?: V1PriceTransformQuantity;
    /**
     * 
     * @type {string}
     * @memberof V1PriceParams
     */
    'type': string;
}

