/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PricePricePb } from './price-price-pb';

/**
 * 
 * @export
 * @interface V1PriceTier
 */
export interface V1PriceTier {
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1PriceTier
     */
    'flat'?: PricePricePb;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1PriceTier
     */
    'unit'?: PricePricePb;
    /**
     * 
     * @type {string}
     * @memberof V1PriceTier
     */
    'upTo'?: string;
}

