/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1ProductCategory
 */
export interface V1ProductCategory {
    /**
     * 
     * @type {string}
     * @memberof V1ProductCategory
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProductCategory
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProductCategory
     */
    'path'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProductCategory
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ProductCategory
     */
    'parent'?: string;
}

