/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1RegisterAuthRequest
 */
export interface V1RegisterAuthRequest {
    /**
     * 
     * @type {string}
     * @memberof V1RegisterAuthRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof V1RegisterAuthRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof V1RegisterAuthRequest
     */
    'confirmPassword': string;
    /**
     * 
     * @type {boolean}
     * @memberof V1RegisterAuthRequest
     */
    'web'?: boolean;
}

