/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OperationStringFilterOperation } from './operation-string-filter-operation';

/**
 * 
 * @export
 * @interface V1SubscriptionFilter
 */
export interface V1SubscriptionFilter {
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1SubscriptionFilter
     */
    'id'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1SubscriptionFilter
     */
    'userId'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1SubscriptionFilter
     */
    'provider'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1SubscriptionFilter
     */
    'providerKey'?: OperationStringFilterOperation;
    /**
     * 
     * @type {Array<V1SubscriptionFilter>}
     * @memberof V1SubscriptionFilter
     */
    'and'?: Array<V1SubscriptionFilter>;
    /**
     * 
     * @type {Array<V1SubscriptionFilter>}
     * @memberof V1SubscriptionFilter
     */
    'or'?: Array<V1SubscriptionFilter>;
}

