/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1SubscriptionItemParams
 */
export interface V1SubscriptionItemParams {
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItemParams
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItemParams
     */
    'priceId'?: string;
    /**
     * 
     * @type {number}
     * @memberof V1SubscriptionItemParams
     */
    'quantity'?: number;
    /**
     * 
     * @type {object}
     * @memberof V1SubscriptionItemParams
     */
    'bizPayload'?: object;
}

