/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1Stock
 */
export interface V1Stock {
    /**
     * 
     * @type {string}
     * @memberof V1Stock
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1Stock
     */
    'inStock'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1Stock
     */
    'level'?: string;
    /**
     * 
     * @type {number}
     * @memberof V1Stock
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof V1Stock
     */
    'deliveryCode'?: string;
}

