/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BlobBlobFile } from './blob-blob-file';
// May contain unused imports in some cases
// @ts-ignore
import type { V1Plan } from './v1-plan';

/**
 * 
 * @export
 * @interface V1TenantInfo
 */
export interface V1TenantInfo {
    /**
     * 
     * @type {string}
     * @memberof V1TenantInfo
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TenantInfo
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TenantInfo
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TenantInfo
     */
    'region'?: string;
    /**
     * 
     * @type {BlobBlobFile}
     * @memberof V1TenantInfo
     */
    'logo'?: BlobBlobFile;
    /**
     * 
     * @type {string}
     * @memberof V1TenantInfo
     */
    'host'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TenantInfo
     */
    'planKey'?: string | null;
    /**
     * 
     * @type {V1Plan}
     * @memberof V1TenantInfo
     */
    'plan'?: V1Plan;
}

