/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1TokenRequest
 */
export interface V1TokenRequest {
    /**
     * 
     * @type {string}
     * @memberof V1TokenRequest
     */
    'grantType'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TokenRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TokenRequest
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1TokenRequest
     */
    'refreshToken'?: string;
}

