/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BlobBlobFile } from './blob-blob-file';
// May contain unused imports in some cases
// @ts-ignore
import type { V1Plan } from './v1-plan';
// May contain unused imports in some cases
// @ts-ignore
import type { V1TenantConnectionString } from './v1-tenant-connection-string';
// May contain unused imports in some cases
// @ts-ignore
import type { V1TenantFeature } from './v1-tenant-feature';

/**
 * 
 * @export
 * @interface V1Tenant
 */
export interface V1Tenant {
    /**
     * 
     * @type {string}
     * @memberof V1Tenant
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Tenant
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Tenant
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Tenant
     */
    'region'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Tenant
     */
    'createdAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1Tenant
     */
    'updatedAt'?: string | null;
    /**
     * 
     * @type {Array<V1TenantConnectionString>}
     * @memberof V1Tenant
     */
    'conn'?: Array<V1TenantConnectionString>;
    /**
     * 
     * @type {Array<V1TenantFeature>}
     * @memberof V1Tenant
     */
    'features'?: Array<V1TenantFeature>;
    /**
     * 
     * @type {BlobBlobFile}
     * @memberof V1Tenant
     */
    'logo'?: BlobBlobFile;
    /**
     * 
     * @type {boolean}
     * @memberof V1Tenant
     */
    'separateDb'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1Tenant
     */
    'host'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Tenant
     */
    'planKey'?: string | null;
    /**
     * 
     * @type {V1Plan}
     * @memberof V1Tenant
     */
    'plan'?: V1Plan;
}

