/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OperationDateFilterOperators } from './operation-date-filter-operators';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationStringFilterOperation } from './operation-string-filter-operation';
// May contain unused imports in some cases
// @ts-ignore
import type { V1RoleFilter } from './v1-role-filter';

/**
 * 
 * @export
 * @interface V1UserFilter
 */
export interface V1UserFilter {
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1UserFilter
     */
    'id'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1UserFilter
     */
    'gender'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationDateFilterOperators}
     * @memberof V1UserFilter
     */
    'birthday'?: OperationDateFilterOperators;
    /**
     * 
     * @type {V1RoleFilter}
     * @memberof V1UserFilter
     */
    'roles'?: V1RoleFilter;
    /**
     * 
     * @type {Array<V1UserFilter>}
     * @memberof V1UserFilter
     */
    'and'?: Array<V1UserFilter>;
    /**
     * 
     * @type {Array<V1UserFilter>}
     * @memberof V1UserFilter
     */
    'or'?: Array<V1UserFilter>;
}

