/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1PriceParams } from './v1-price-params';

/**
 * 
 * @export
 * @interface V1UpdatePlan
 */
export interface V1UpdatePlan {
    /**
     * 
     * @type {string}
     * @memberof V1UpdatePlan
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdatePlan
     */
    'displayName': string;
    /**
     * 
     * @type {boolean}
     * @memberof V1UpdatePlan
     */
    'active'?: boolean;
    /**
     * 
     * @type {Array<V1PriceParams>}
     * @memberof V1UpdatePlan
     */
    'prices'?: Array<V1PriceParams>;
    /**
     * 
     * @type {number}
     * @memberof V1UpdatePlan
     */
    'sort'?: number;
}

