/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1UserCreateTenantRequest
 */
export interface V1UserCreateTenantRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UserCreateTenantRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof V1UserCreateTenantRequest
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserCreateTenantRequest
     */
    'region'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserCreateTenantRequest
     */
    'logo'?: string;
}

