/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1TenantConnectionString } from './v1-tenant-connection-string';
// May contain unused imports in some cases
// @ts-ignore
import type { V1TenantFeature } from './v1-tenant-feature';

/**
 * 
 * @export
 * @interface V1UpdateTenant
 */
export interface V1UpdateTenant {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateTenant
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateTenant
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateTenant
     */
    'displayName'?: string;
    /**
     * 
     * @type {Array<V1TenantConnectionString>}
     * @memberof V1UpdateTenant
     */
    'conn'?: Array<V1TenantConnectionString>;
    /**
     * 
     * @type {Array<V1TenantFeature>}
     * @memberof V1UpdateTenant
     */
    'features'?: Array<V1TenantFeature>;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateTenant
     */
    'logo'?: string;
}

