/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1Effect } from './v1-effect';

/**
 * 
 * @export
 * @interface V1UpdateRolePermissionAcl
 */
export interface V1UpdateRolePermissionAcl {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateRolePermissionAcl
     */
    'namespace'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateRolePermissionAcl
     */
    'resource'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateRolePermissionAcl
     */
    'action'?: string;
    /**
     * 
     * @type {V1Effect}
     * @memberof V1UpdateRolePermissionAcl
     */
    'effect'?: V1Effect;
}



