/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1UpdateUser
 */
export interface V1UpdateUser {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateUser
     */
    'id': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1UpdateUser
     */
    'rolesId'?: Array<string>;
}

