/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1TenantInfo } from './v1-tenant-info';

/**
 * 
 * @export
 * @interface V1UserTenant
 */
export interface V1UserTenant {
    /**
     * 
     * @type {string}
     * @memberof V1UserTenant
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserTenant
     */
    'tenantId'?: string;
    /**
     * 
     * @type {V1TenantInfo}
     * @memberof V1UserTenant
     */
    'tenant'?: V1TenantInfo;
    /**
     * 
     * @type {boolean}
     * @memberof V1UserTenant
     */
    'isHost'?: boolean;
}

