/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DataDynamicValue } from './data-dynamic-value';

/**
 * 
 * @export
 * @interface V1UpdateSettings
 */
export interface V1UpdateSettings {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateSettings
     */
    'key'?: string;
    /**
     * 
     * @type {DataDynamicValue}
     * @memberof V1UpdateSettings
     */
    'value'?: DataDynamicValue;
    /**
     * 
     * @type {boolean}
     * @memberof V1UpdateSettings
     */
    'reset'?: boolean;
}

