/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1ValidatePasswordReply
 */
export interface V1ValidatePasswordReply {
    /**
     * 
     * @type {boolean}
     * @memberof V1ValidatePasswordReply
     */
    'ok'?: boolean;
}

