/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1WechatMiniProgramPhoneCodeReq
 */
export interface V1WechatMiniProgramPhoneCodeReq {
    /**
     * 
     * @type {string}
     * @memberof V1WechatMiniProgramPhoneCodeReq
     */
    'appId': string;
    /**
     * 
     * @type {string}
     * @memberof V1WechatMiniProgramPhoneCodeReq
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof V1WechatMiniProgramPhoneCodeReq
     */
    'nextToken': string;
}

