/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1WebLoginAuthRequest
 */
export interface V1WebLoginAuthRequest {
    /**
     * 
     * @type {string}
     * @memberof V1WebLoginAuthRequest
     */
    'email': string | null;
    /**
     * 
     * @type {string}
     * @memberof V1WebLoginAuthRequest
     */
    'password': string;
    /**
     * 
     * @type {boolean}
     * @memberof V1WebLoginAuthRequest
     */
    'remember'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1WebLoginAuthRequest
     */
    'challenge'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1WebLoginAuthRequest
     */
    'reject'?: boolean;
}

