/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1TokenReply } from './v1-token-reply';

/**
 * 
 * @export
 * @interface V1WeChatLoginReply
 */
export interface V1WeChatLoginReply {
    /**
     * 
     * @type {string}
     * @memberof V1WeChatLoginReply
     */
    'next'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1WeChatLoginReply
     */
    'nextToken'?: string;
    /**
     * 
     * @type {V1TokenReply}
     * @memberof V1WeChatLoginReply
     */
    'token'?: V1TokenReply;
}

