/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ComponentExtensionSpec } from './v1beta1-component-extension-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1HuggingFaceRuntimeSpec } from './v1beta1-hugging-face-runtime-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1LightGBMSpec } from './v1beta1-light-gbmspec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelServerSpec } from './v1beta1-model-server-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ONNXRuntimeSpec } from './v1beta1-onnxruntime-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1PMMLSpec } from './v1beta1-pmmlspec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1PaddleServerSpec } from './v1beta1-paddle-server-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1SKLearnSpec } from './v1beta1-sklearn-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1TFServingSpec } from './v1beta1-tfserving-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1TorchServeSpec } from './v1beta1-torch-serve-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1TritonSpec } from './v1beta1-triton-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1XGBoostSpec } from './v1beta1-xgboost-spec';

/**
 * 
 * @export
 * @interface V1beta1PredictorSpec
 */
export interface V1beta1PredictorSpec {
    /**
     * 
     * @type {string}
     * @memberof V1beta1PredictorSpec
     */
    'modelId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1PredictorSpec
     */
    'modelName'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1PredictorSpec
     */
    'modelVersion'?: string;
    /**
     * 
     * @type {V1beta1SKLearnSpec}
     * @memberof V1beta1PredictorSpec
     */
    'sklearn'?: V1beta1SKLearnSpec;
    /**
     * 
     * @type {V1beta1XGBoostSpec}
     * @memberof V1beta1PredictorSpec
     */
    'xgboost'?: V1beta1XGBoostSpec;
    /**
     * 
     * @type {V1beta1TFServingSpec}
     * @memberof V1beta1PredictorSpec
     */
    'tfserving'?: V1beta1TFServingSpec;
    /**
     * 
     * @type {V1beta1TorchServeSpec}
     * @memberof V1beta1PredictorSpec
     */
    'torchserve'?: V1beta1TorchServeSpec;
    /**
     * 
     * @type {V1beta1TritonSpec}
     * @memberof V1beta1PredictorSpec
     */
    'triton'?: V1beta1TritonSpec;
    /**
     * 
     * @type {V1beta1ONNXRuntimeSpec}
     * @memberof V1beta1PredictorSpec
     */
    'onnxRuntime'?: V1beta1ONNXRuntimeSpec;
    /**
     * 
     * @type {V1beta1HuggingFaceRuntimeSpec}
     * @memberof V1beta1PredictorSpec
     */
    'huggingface'?: V1beta1HuggingFaceRuntimeSpec;
    /**
     * 
     * @type {V1beta1PMMLSpec}
     * @memberof V1beta1PredictorSpec
     */
    'pmml'?: V1beta1PMMLSpec;
    /**
     * 
     * @type {V1beta1LightGBMSpec}
     * @memberof V1beta1PredictorSpec
     */
    'lightgbm'?: V1beta1LightGBMSpec;
    /**
     * 
     * @type {V1beta1PaddleServerSpec}
     * @memberof V1beta1PredictorSpec
     */
    'paddleserver'?: V1beta1PaddleServerSpec;
    /**
     * 
     * @type {V1beta1ModelServerSpec}
     * @memberof V1beta1PredictorSpec
     */
    'modelserver'?: V1beta1ModelServerSpec;
    /**
     * 
     * @type {V1beta1ComponentExtensionSpec}
     * @memberof V1beta1PredictorSpec
     */
    'componentExtension'?: V1beta1ComponentExtensionSpec;
}

