/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LoggerSpecLoggerType } from './logger-spec-logger-type';

/**
 * 
 * @export
 * @interface V1beta1LoggerSpec
 */
export interface V1beta1LoggerSpec {
    /**
     * 
     * @type {string}
     * @memberof V1beta1LoggerSpec
     */
    'url'?: string;
    /**
     * 
     * @type {LoggerSpecLoggerType}
     * @memberof V1beta1LoggerSpec
     */
    'loggerType'?: LoggerSpecLoggerType;
}



