/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1BasicDeploymentConfig } from './v1beta1-basic-deployment-config';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelMetadata } from './v1beta1-model-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelTag } from './v1beta1-model-tag';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelVersion } from './v1beta1-model-version';

/**
 * 
 * @export
 * @interface V1beta1Model
 */
export interface V1beta1Model {
    /**
     * 
     * @type {string}
     * @memberof V1beta1Model
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Model
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Model
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Model
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Model
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Model
     */
    'tenantId'?: string;
    /**
     * 
     * @type {Array<V1beta1ModelVersion>}
     * @memberof V1beta1Model
     */
    'versions'?: Array<V1beta1ModelVersion>;
    /**
     * 
     * @type {Array<V1beta1ModelTag>}
     * @memberof V1beta1Model
     */
    'tags'?: Array<V1beta1ModelTag>;
    /**
     * 
     * @type {V1beta1BasicDeploymentConfig}
     * @memberof V1beta1Model
     */
    'deploymentConfig'?: V1beta1BasicDeploymentConfig;
    /**
     * 
     * @type {Array<V1beta1ModelMetadata>}
     * @memberof V1beta1Model
     */
    'metadata'?: Array<V1beta1ModelMetadata>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1beta1Model
     */
    'deploymentIds'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof V1beta1Model
     */
    'internal'?: boolean;
}

