/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelVersion } from './v1beta1-model-version';

/**
 * 
 * @export
 * @interface V1beta1ListVersionReply
 */
export interface V1beta1ListVersionReply {
    /**
     * 
     * @type {number}
     * @memberof V1beta1ListVersionReply
     */
    'totalSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1beta1ListVersionReply
     */
    'filterSize'?: number;
    /**
     * 
     * @type {Array<V1beta1ModelVersion>}
     * @memberof V1beta1ListVersionReply
     */
    'versions'?: Array<V1beta1ModelVersion>;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListVersionReply
     */
    'nextAfterPageToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListVersionReply
     */
    'nextBeforePageToken'?: string | null;
}

