/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V1beta1ModelServingRuntime = {
    Unspecified: 'MODEL_SERVING_RUNTIME_UNSPECIFIED',
    LightgbmMlserver: 'MODEL_SERVING_RUNTIME_LIGHTGBM_MLSERVER',
    LightgbmModelserver: 'MODEL_SERVING_RUNTIME_LIGHTGBM_MODELSERVER',
    MlflowModelserver: 'MODEL_SERVING_RUNTIME_MLFLOW_MODELSERVER',
    PmmlModelserver: 'MODEL_SERVING_RUNTIME_PMML_MODELSERVER',
    SklearnMlserver: 'MODEL_SERVING_RUNTIME_SKLEARN_MLSERVER',
    SklearnModelserver: 'MODEL_SERVING_RUNTIME_SKLEARN_MODELSERVER',
    Tfserving: 'MODEL_SERVING_RUNTIME_TFSERVING',
    Torchserver: 'MODEL_SERVING_RUNTIME_TORCHSERVER',
    TritonInferenceServer: 'MODEL_SERVING_RUNTIME_TRITON_INFERENCE_SERVER',
    XgboostMlserver: 'MODEL_SERVING_RUNTIME_XGBOOST_MLSERVER',
    XgboostModelserver: 'MODEL_SERVING_RUNTIME_XGBOOST_MODELSERVER',
    HuggingfaceModelserver: 'MODEL_SERVING_RUNTIME_HUGGINGFACE_MODELSERVER',
    HuggingfaceVllmModelServer: 'MODEL_SERVING_RUNTIME_HUGGINGFACE_VLLM_MODEL_SERVER',
    Custom: 'MODEL_SERVING_RUNTIME_CUSTOM'
} as const;

export type V1beta1ModelServingRuntime = typeof V1beta1ModelServingRuntime[keyof typeof V1beta1ModelServingRuntime];



