/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1InferenceServiceSpec } from './v1beta1-inference-service-spec';

/**
 * 
 * @export
 * @interface V1beta1CreateInferenceRequest
 */
export interface V1beta1CreateInferenceRequest {
    /**
     * 
     * @type {V1beta1InferenceServiceSpec}
     * @memberof V1beta1CreateInferenceRequest
     */
    'spec'?: V1beta1InferenceServiceSpec;
    /**
     * 
     * @type {string}
     * @memberof V1beta1CreateInferenceRequest
     */
    'instanceType'?: string;
}

