/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1beta1BatcherSpec
 */
export interface V1beta1BatcherSpec {
    /**
     * 
     * @type {number}
     * @memberof V1beta1BatcherSpec
     */
    'maxBatchSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1beta1BatcherSpec
     */
    'maxLatency'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1beta1BatcherSpec
     */
    'timeout'?: number;
}

