/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1StorageSpec } from './v1beta1-storage-spec';

/**
 * 
 * @export
 * @interface V1beta1ExplainerExtensionSpec
 */
export interface V1beta1ExplainerExtensionSpec {
    /**
     * 
     * @type {string}
     * @memberof V1beta1ExplainerExtensionSpec
     */
    'storageUri'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ExplainerExtensionSpec
     */
    'runtimeVersion'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof V1beta1ExplainerExtensionSpec
     */
    'config'?: { [key: string]: string; };
    /**
     * 
     * @type {V1beta1StorageSpec}
     * @memberof V1beta1ExplainerExtensionSpec
     */
    'storage'?: V1beta1StorageSpec;
}

