/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelFilter } from './v1beta1-model-filter';

/**
 * 
 * @export
 * @interface V1beta1ListModelRequest
 */
export interface V1beta1ListModelRequest {
    /**
     * 
     * @type {number}
     * @memberof V1beta1ListModelRequest
     */
    'pageOffset'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1beta1ListModelRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListModelRequest
     */
    'search'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1beta1ListModelRequest
     */
    'sort'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListModelRequest
     */
    'fields'?: string;
    /**
     * 
     * @type {V1beta1ModelFilter}
     * @memberof V1beta1ListModelRequest
     */
    'filter'?: V1beta1ModelFilter;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListModelRequest
     */
    'afterPageToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListModelRequest
     */
    'beforePageToken'?: string;
}

