/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1PredictorExtensionSpec } from './v1beta1-predictor-extension-spec';

/**
 * 
 * @export
 * @interface V1beta1LightGBMSpec
 */
export interface V1beta1LightGBMSpec {
    /**
     * 
     * @type {V1beta1PredictorExtensionSpec}
     * @memberof V1beta1LightGBMSpec
     */
    'predictorExtension'?: V1beta1PredictorExtensionSpec;
}

