/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ComponentStatusSpec } from './v1beta1-component-status-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1InferenceServiceStatusStatus } from './v1beta1-inference-service-status-status';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelStatus } from './v1beta1-model-status';

/**
 * 
 * @export
 * @interface V1beta1InferenceServiceStatus
 */
export interface V1beta1InferenceServiceStatus {
    /**
     * 
     * @type {V1beta1InferenceServiceStatusStatus}
     * @memberof V1beta1InferenceServiceStatus
     */
    'status'?: V1beta1InferenceServiceStatusStatus;
    /**
     * 
     * @type {string}
     * @memberof V1beta1InferenceServiceStatus
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1InferenceServiceStatus
     */
    'url'?: string;
    /**
     * 
     * @type {{ [key: string]: V1beta1ComponentStatusSpec; }}
     * @memberof V1beta1InferenceServiceStatus
     */
    'componentStatuses'?: { [key: string]: V1beta1ComponentStatusSpec; };
    /**
     * 
     * @type {V1beta1ModelStatus}
     * @memberof V1beta1InferenceServiceStatus
     */
    'modelStatus'?: V1beta1ModelStatus;
}



