/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1Framework } from './v1beta1-framework';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelServingRuntime } from './v1beta1-model-serving-runtime';

/**
 * 
 * @export
 * @interface V1beta1BasicDeploymentConfig
 */
export interface V1beta1BasicDeploymentConfig {
    /**
     * 
     * @type {V1beta1ModelServingRuntime}
     * @memberof V1beta1BasicDeploymentConfig
     */
    'runtime'?: V1beta1ModelServingRuntime;
    /**
     * 
     * @type {V1beta1Framework}
     * @memberof V1beta1BasicDeploymentConfig
     */
    'framework'?: V1beta1Framework;
    /**
     * 
     * @type {number}
     * @memberof V1beta1BasicDeploymentConfig
     */
    'minReplicas'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1beta1BasicDeploymentConfig
     */
    'maxReplicas'?: number;
}



