/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1beta1ComponentStatusSpec
 */
export interface V1beta1ComponentStatusSpec {
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentStatusSpec
     */
    'latestReadyRevision'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentStatusSpec
     */
    'latestCreatedRevision'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentStatusSpec
     */
    'previousRolledOutRevision'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentStatusSpec
     */
    'latestRolledOutRevision'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentStatusSpec
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentStatusSpec
     */
    'restUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentStatusSpec
     */
    'grpcUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentStatusSpec
     */
    'address'?: string;
}

