/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1BasicDeploymentConfig } from './v1beta1-basic-deployment-config';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelMetadata } from './v1beta1-model-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelTag } from './v1beta1-model-tag';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelVersion } from './v1beta1-model-version';

/**
 * 
 * @export
 * @interface V1beta1CreateModelRequest
 */
export interface V1beta1CreateModelRequest {
    /**
     * 
     * @type {string}
     * @memberof V1beta1CreateModelRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1CreateModelRequest
     */
    'description'?: string;
    /**
     * 
     * @type {Array<V1beta1ModelTag>}
     * @memberof V1beta1CreateModelRequest
     */
    'tags'?: Array<V1beta1ModelTag>;
    /**
     * 
     * @type {V1beta1BasicDeploymentConfig}
     * @memberof V1beta1CreateModelRequest
     */
    'basicDeploymentConfig'?: V1beta1BasicDeploymentConfig;
    /**
     * 
     * @type {Array<V1beta1ModelMetadata>}
     * @memberof V1beta1CreateModelRequest
     */
    'metadata'?: Array<V1beta1ModelMetadata>;
    /**
     * 
     * @type {V1beta1ModelVersion}
     * @memberof V1beta1CreateModelRequest
     */
    'initialVersion'?: V1beta1ModelVersion;
}

