/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V1beta1Framework = {
    Unspecified: 'FRAMEWORK_UNSPECIFIED',
    Tensorflow: 'FRAMEWORK_TENSORFLOW',
    Pytorch: 'FRAMEWORK_PYTORCH',
    Sklearn: 'FRAMEWORK_SKLEARN',
    Xgboost: 'FRAMEWORK_XGBOOST',
    Lightgbm: 'FRAMEWORK_LIGHTGBM',
    Onnx: 'FRAMEWORK_ONNX',
    Triton: 'FRAMEWORK_TRITON',
    Pmml: 'FRAMEWORK_PMML',
    Custom: 'FRAMEWORK_CUSTOM'
} as const;

export type V1beta1Framework = typeof V1beta1Framework[keyof typeof V1beta1Framework];



