/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1beta1ListInferenceRequest
 */
export interface V1beta1ListInferenceRequest {
    /**
     * 
     * @type {number}
     * @memberof V1beta1ListInferenceRequest
     */
    'pageOffset'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1beta1ListInferenceRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListInferenceRequest
     */
    'search'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1beta1ListInferenceRequest
     */
    'sort'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListInferenceRequest
     */
    'fields'?: string;
    /**
     * 
     * @type {object}
     * @memberof V1beta1ListInferenceRequest
     */
    'filter'?: object;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListInferenceRequest
     */
    'afterPageToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ListInferenceRequest
     */
    'beforePageToken'?: string;
}

