/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ComponentExtensionSpecScaleMetric } from './component-extension-spec-scale-metric';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1BatcherSpec } from './v1beta1-batcher-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1LoggerSpec } from './v1beta1-logger-spec';

/**
 * 
 * @export
 * @interface V1beta1ComponentExtensionSpec
 */
export interface V1beta1ComponentExtensionSpec {
    /**
     * 
     * @type {number}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'minReplicas'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'maxReplicas'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'scaleTarget'?: number | null;
    /**
     * 
     * @type {ComponentExtensionSpecScaleMetric}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'scaleMetric'?: ComponentExtensionSpecScaleMetric;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'containerConcurrency'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'timeout'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'canaryWeight'?: number | null;
    /**
     * 
     * @type {V1beta1LoggerSpec}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'logger'?: V1beta1LoggerSpec;
    /**
     * 
     * @type {V1beta1BatcherSpec}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'batcher'?: V1beta1BatcherSpec;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'labels'?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof V1beta1ComponentExtensionSpec
     */
    'annotations'?: { [key: string]: string; };
}



