/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ARTExplainerSpec } from './v1beta1-artexplainer-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ComponentExtensionSpec } from './v1beta1-component-extension-spec';

/**
 * 
 * @export
 * @interface V1beta1ExplainerSpec
 */
export interface V1beta1ExplainerSpec {
    /**
     * 
     * @type {V1beta1ARTExplainerSpec}
     * @memberof V1beta1ExplainerSpec
     */
    'artExplainer'?: V1beta1ARTExplainerSpec;
    /**
     * 
     * @type {V1beta1ComponentExtensionSpec}
     * @memberof V1beta1ExplainerSpec
     */
    'componentExtension'?: V1beta1ComponentExtensionSpec;
}

