/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1CustomModelVersionMetadata } from './v1beta1-custom-model-version-metadata';

/**
 * 
 * @export
 * @interface V1beta1ModelVersionMetadata
 */
export interface V1beta1ModelVersionMetadata {
    /**
     * 
     * @type {string}
     * @memberof V1beta1ModelVersionMetadata
     */
    'changelog'?: string;
    /**
     * 
     * @type {Array<V1beta1CustomModelVersionMetadata>}
     * @memberof V1beta1ModelVersionMetadata
     */
    'customMetadata'?: Array<V1beta1CustomModelVersionMetadata>;
}

