/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V1beta1InferenceServiceStatusStatus = {
    Unspecified: 'STATUS_UNSPECIFIED',
    PredictorReady: 'STATUS_PREDICTOR_READY',
    ExplainerReady: 'STATUS_EXPLAINER_READY',
    TransformerReady: 'STATUS_TRANSFORMER_READY',
    RoutesReady: 'STATUS_ROUTES_READY',
    LatestDeploymentReady: 'STATUS_LATEST_DEPLOYMENT_READY',
    AllComponentsReady: 'STATUS_ALL_COMPONENTS_READY'
} as const;

export type V1beta1InferenceServiceStatusStatus = typeof V1beta1InferenceServiceStatusStatus[keyof typeof V1beta1InferenceServiceStatusStatus];



