/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1InferenceServiceSpec } from './v1beta1-inference-service-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1InferenceServiceStatus } from './v1beta1-inference-service-status';

/**
 * 
 * @export
 * @interface V1beta1Inference
 */
export interface V1beta1Inference {
    /**
     * 
     * @type {string}
     * @memberof V1beta1Inference
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Inference
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Inference
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Inference
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Inference
     */
    'instanceType'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1Inference
     */
    'version'?: string;
    /**
     * 
     * @type {V1beta1InferenceServiceSpec}
     * @memberof V1beta1Inference
     */
    'spec'?: V1beta1InferenceServiceSpec;
    /**
     * 
     * @type {V1beta1InferenceServiceStatus}
     * @memberof V1beta1Inference
     */
    'status'?: V1beta1InferenceServiceStatus;
}

