/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ARTExplainerSpecARTExplainerType } from './artexplainer-spec-artexplainer-type';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ExplainerExtensionSpec } from './v1beta1-explainer-extension-spec';

/**
 * 
 * @export
 * @interface V1beta1ARTExplainerSpec
 */
export interface V1beta1ARTExplainerSpec {
    /**
     * 
     * @type {ARTExplainerSpecARTExplainerType}
     * @memberof V1beta1ARTExplainerSpec
     */
    'explainerType'?: ARTExplainerSpecARTExplainerType;
    /**
     * 
     * @type {V1beta1ExplainerExtensionSpec}
     * @memberof V1beta1ARTExplainerSpec
     */
    'explainerExtension'?: V1beta1ExplainerExtensionSpec;
}



