/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1beta1StorageSpec
 */
export interface V1beta1StorageSpec {
    /**
     * 
     * @type {string}
     * @memberof V1beta1StorageSpec
     */
    'path'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1beta1StorageSpec
     */
    'schemePath'?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof V1beta1StorageSpec
     */
    'parameters'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof V1beta1StorageSpec
     */
    'key'?: string | null;
}

