/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PredictorExtensionSpecInferenceServiceProtocol } from './predictor-extension-spec-inference-service-protocol';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1StorageSpec } from './v1beta1-storage-spec';

/**
 * 
 * @export
 * @interface V1beta1PredictorExtensionSpec
 */
export interface V1beta1PredictorExtensionSpec {
    /**
     * 
     * @type {string}
     * @memberof V1beta1PredictorExtensionSpec
     */
    'storageUri'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1beta1PredictorExtensionSpec
     */
    'runtimeVersion'?: string | null;
    /**
     * 
     * @type {PredictorExtensionSpecInferenceServiceProtocol}
     * @memberof V1beta1PredictorExtensionSpec
     */
    'protocol'?: PredictorExtensionSpecInferenceServiceProtocol;
    /**
     * 
     * @type {V1beta1StorageSpec}
     * @memberof V1beta1PredictorExtensionSpec
     */
    'storage'?: V1beta1StorageSpec;
}



