/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelVersionMetadata } from './v1beta1-model-version-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ModelVersionTag } from './v1beta1-model-version-tag';

/**
 * 
 * @export
 * @interface V1beta1ModelVersion
 */
export interface V1beta1ModelVersion {
    /**
     * 
     * @type {string}
     * @memberof V1beta1ModelVersion
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ModelVersion
     */
    'modelId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ModelVersion
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ModelVersion
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ModelVersion
     */
    'storageUri'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ModelVersion
     */
    'modelSize'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1beta1ModelVersion
     */
    'internal'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ModelVersion
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1ModelVersion
     */
    'createdBy'?: string;
    /**
     * 
     * @type {V1beta1ModelVersionMetadata}
     * @memberof V1beta1ModelVersion
     */
    'modelVersionMetadata'?: V1beta1ModelVersionMetadata;
    /**
     * 
     * @type {Array<V1beta1ModelVersionTag>}
     * @memberof V1beta1ModelVersion
     */
    'tags'?: Array<V1beta1ModelVersionTag>;
}

