/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1beta1CreateInternalVersionItem
 */
export interface V1beta1CreateInternalVersionItem {
    /**
     * 
     * @type {string}
     * @memberof V1beta1CreateInternalVersionItem
     */
    'versionNumber': string;
    /**
     * 
     * @type {string}
     * @memberof V1beta1CreateInternalVersionItem
     */
    'changelog'?: string;
    /**
     * 
     * @type {object}
     * @memberof V1beta1CreateInternalVersionItem
     */
    'customMetadata'?: object;
}

