/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelStatusFailureInfo } from './model-status-failure-info';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelStatusModelCopies } from './model-status-model-copies';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelStatusModelRevisionStates } from './model-status-model-revision-states';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelStatusTransitionStatus } from './model-status-transition-status';

/**
 * 
 * @export
 * @interface V1beta1ModelStatus
 */
export interface V1beta1ModelStatus {
    /**
     * 
     * @type {ModelStatusTransitionStatus}
     * @memberof V1beta1ModelStatus
     */
    'transitionStatus'?: ModelStatusTransitionStatus;
    /**
     * 
     * @type {ModelStatusModelRevisionStates}
     * @memberof V1beta1ModelStatus
     */
    'modelRevisionStates'?: ModelStatusModelRevisionStates;
    /**
     * 
     * @type {ModelStatusFailureInfo}
     * @memberof V1beta1ModelStatus
     */
    'failureInfo'?: ModelStatusFailureInfo;
    /**
     * 
     * @type {ModelStatusModelCopies}
     * @memberof V1beta1ModelStatus
     */
    'modelCopies'?: ModelStatusModelCopies;
}



