/* tslint:disable */
/* eslint-disable */
/**
 * Inference
 * Inference API
 *
 * The version of the OpenAPI document: v1beta1
 * Contact: support@deployo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1ExplainerSpec } from './v1beta1-explainer-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1PredictorSpec } from './v1beta1-predictor-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { V1beta1TransformerSpec } from './v1beta1-transformer-spec';

/**
 * 
 * @export
 * @interface V1beta1InferenceServiceSpec
 */
export interface V1beta1InferenceServiceSpec {
    /**
     * 
     * @type {V1beta1PredictorSpec}
     * @memberof V1beta1InferenceServiceSpec
     */
    'predictor'?: V1beta1PredictorSpec;
    /**
     * 
     * @type {V1beta1ExplainerSpec}
     * @memberof V1beta1InferenceServiceSpec
     */
    'explainer'?: V1beta1ExplainerSpec;
    /**
     * 
     * @type {V1beta1TransformerSpec}
     * @memberof V1beta1InferenceServiceSpec
     */
    'transformer'?: V1beta1TransformerSpec;
}

